from enum import Enum


class VoiceNameByLanguageEnum:
    class AFRIKAANS_SOUTH_AFRICA(str, Enum):
        ADRI = "Adri"
        """Female voice for Afrikaans (South Africa) (Free voice)"""
        WILLEM = "Willem"
        """Male voice for Afrikaans (South Africa) (Free voice)"""

    class ALBANIAN_ALBANIA(str, Enum):
        ANILA = "Anila"
        """Female voice for Albanian (Albania) (Free voice)"""
        ILIR = "Ilir"
        """Male voice for Albanian (Albania) (Free voice)"""

    class AMHARIC_ETHIOPIA(str, Enum):
        AMEHA = "Ameha"
        """Male voice for Amharic (Ethiopia) (Free voice)"""
        MEKDES = "Mekdes"
        """Female voice for Amharic (Ethiopia) (Free voice)"""

    class ARABIC_ALGERIA(str, Enum):
        AMINA = "Amina"
        """Female voice for Arabic (Algeria) (Free voice)"""
        ISMAEL = "Ismael"
        """Male voice for Arabic (Algeria) (Free voice)"""

    class ARABIC_BAHRAIN(str, Enum):
        ALI = "Ali"
        """Male voice for Arabic (Bahrain) (Free voice)"""
        LAILA = "Laila"
        """Female voice for Arabic (Bahrain) (Free voice)"""

    class ARABIC_EGYPT(str, Enum):
        SALMA = "Salma"
        """Female voice for Arabic (Egypt) (Free voice)"""
        SHAKIR = "Shakir"
        """Male voice for Arabic (Egypt) (Free voice)"""

    class ARABIC_IRAQ(str, Enum):
        BASSEL = "Bassel"
        """Male voice for Arabic (Iraq) (Free voice)"""
        RANA = "Rana"
        """Female voice for Arabic (Iraq) (Free voice)"""

    class ARABIC_JORDAN(str, Enum):
        SANA = "Sana"
        """Female voice for Arabic (Jordan) (Free voice)"""
        TAIM = "Taim"
        """Male voice for Arabic (Jordan) (Free voice)"""

    class ARABIC_KUWAIT(str, Enum):
        FAHED = "Fahed"
        """Male voice for Arabic (Kuwait) (Free voice)"""
        NOURA = "Noura"
        """Female voice for Arabic (Kuwait) (Free voice)"""

    class ARABIC_LEBANON(str, Enum):
        LAYLA = "Layla"
        """Female voice for Arabic (Lebanon) (Free voice)"""
        RAMI = "Rami"
        """Male voice for Arabic (Lebanon) (Free voice)"""

    class ARABIC_LIBYA(str, Enum):
        IMAN = "Iman"
        """Female voice for Arabic (Libya) (Free voice)"""
        OMAR = "Omar"
        """Male voice for Arabic (Libya) (Free voice)"""

    class ARABIC_MOROCCO(str, Enum):
        JAMAL = "Jamal"
        """Male voice for Arabic (Morocco) (Free voice)"""
        MOUNA = "Mouna"
        """Female voice for Arabic (Morocco) (Free voice)"""

    class ARABIC_OMAN(str, Enum):
        ABDULLAH = "Abdullah"
        """Male voice for Arabic (Oman) (Free voice)"""
        AYSHA = "Aysha"
        """Female voice for Arabic (Oman) (Free voice)"""

    class ARABIC_QATAR(str, Enum):
        AMAL = "Amal"
        """Female voice for Arabic (Qatar) (Free voice)"""
        MOAZ = "Moaz"
        """Male voice for Arabic (Qatar) (Free voice)"""

    class ARABIC_SAUDI_ARABIA(str, Enum):
        HALA = "Hala"
        """Female voice for Arabic (Saudi Arabia) (Free voice)"""
        HAMED = "Hamed"
        """Male voice for Arabic (Saudi Arabia) (Free voice)"""
        ZARIYAH = "Zariyah"
        """Female voice for Arabic (Saudi Arabia) (Free voice)"""
        ZAYD = "Zayd"
        """Male voice for Arabic (Saudi Arabia) (Free voice)"""
        ZEINA = "Zeina"
        """Female voice for Arabic (Saudi Arabia) (Free voice)"""

    class ARABIC_SYRIA(str, Enum):
        AMANY = "Amany"
        """Female voice for Arabic (Syria) (Free voice)"""
        LAITH = "Laith"
        """Male voice for Arabic (Syria) (Free voice)"""

    class ARABIC_TUNISIA(str, Enum):
        HEDI = "Hedi"
        """Male voice for Arabic (Tunisia) (Free voice)"""
        REEM = "Reem"
        """Female voice for Arabic (Tunisia) (Free voice)"""

    class ARABIC_UNITED_ARAB_EMIRATES(str, Enum):
        FATIMA = "Fatima"
        """Female voice for Arabic (United Arab Emirates) (Free voice)"""
        HAMDAN = "Hamdan"
        """Male voice for Arabic (United Arab Emirates) (Free voice)"""

    class ARABIC_YEMEN(str, Enum):
        MARYAM = "Maryam"
        """Female voice for Arabic (Yemen) (Free voice)"""
        SALEH = "Saleh"
        """Male voice for Arabic (Yemen) (Free voice)"""

    class ARMENIAN_ARMENIA(str, Enum):
        ANAHIT = "Anahit"
        """Female voice for Armenian (Armenia) (Free voice)"""
        HAYK = "Hayk"
        """Male voice for Armenian (Armenia) (Free voice)"""

    class ASSAMESE_INDIA(str, Enum):
        PRIYOM = "Priyom"
        """Male voice for Assamese (India) (Free voice)"""
        YASHICA = "Yashica"
        """Female voice for Assamese (India) (Free voice)"""

    class AZERBAIJANI_LATIN_AZERBAIJAN(str, Enum):
        BABEK = "Babek"
        """Male voice for Azerbaijani (Latin, Azerbaijan) (Free voice)"""
        BANU = "Banu"
        """Female voice for Azerbaijani (Latin, Azerbaijan) (Free voice)"""

    class BANGLA_BANGLADESH(str, Enum):
        NABANITA = "Nabanita"
        """Female voice for Bangla (Bangladesh) (Free voice)"""
        PRADEEP = "Pradeep"
        """Male voice for Bangla (Bangladesh) (Free voice)"""

    class BASQUE(str, Enum):
        AINHOA = "Ainhoa"
        """Female voice for Basque (Free voice)"""
        ANDER = "Ander"
        """Male voice for Basque (Free voice)"""

    class BENGALI_INDIA(str, Enum):
        BASHKAR = "Bashkar"
        """Male voice for Bengali (India) (Free voice)"""
        TANISHAA = "Tanishaa"
        """Female voice for Bengali (India) (Free voice)"""

    class BOSNIAN_BOSNIA_AND_HERZEGOVINA(str, Enum):
        GORAN = "Goran"
        """Male voice for Bosnian (Bosnia and Herzegovina) (Free voice)"""
        VESNA = "Vesna"
        """Female voice for Bosnian (Bosnia and Herzegovina) (Free voice)"""

    class BULGARIAN_BULGARIA(str, Enum):
        BORISLAV = "Borislav"
        """Male voice for Bulgarian (Bulgaria) (Free voice)"""
        KALINA = "Kalina"
        """Female voice for Bulgarian (Bulgaria) (Free voice)"""

    class BURMESE_MYANMAR(str, Enum):
        NILAR = "Nilar"
        """Female voice for Burmese (Myanmar) (Free voice)"""
        THIHA = "Thiha"
        """Male voice for Burmese (Myanmar) (Free voice)"""

    class CATALAN(str, Enum):
        ALBA = "Alba"
        """Female voice for Catalan (Free voice)"""
        ARLET = "Arlet"
        """Female voice for Catalan (Free voice)"""
        ENRIC = "Enric"
        """Male voice for Catalan (Free voice)"""
        JOANA = "Joana"
        """Female voice for Catalan (Free voice)"""

    class CHINESE_CANTONESE(str, Enum):
        HIUJIN = "Hiujin"
        """Female voice for Chinese (Cantonese) (Free voice)"""

    class CHINESE_CANTONESE_SIMPLIFIED(str, Enum):
        XIAOMIN = "XiaoMin"
        """Female voice for Chinese (Cantonese, Simplified) (Free voice)"""
        YUNSONG = "YunSong"
        """Male voice for Chinese (Cantonese, Simplified) (Free voice)"""

    class CHINESE_CANTONESE_TRADITIONAL(str, Enum):
        HIUGAAI = "HiuGaai"
        """Female voice for Chinese (Cantonese, Traditional) (Free voice)"""
        HIUMAAN = "HiuMaan"
        """Female voice for Chinese (Cantonese, Traditional) (Free voice)"""
        WANLUNG = "WanLung"
        """Male voice for Chinese (Cantonese, Traditional) (Free voice)"""

    class CHINESE_JILU_MANDARIN_SIMPLIFIED(str, Enum):
        YUNXIANG = "Yunxiang"
        """Male voice for Chinese (Jilu Mandarin, Simplified) (Free voice)"""

    class CHINESE_MANDARIN(str, Enum):
        ZHIYU = "Zhiyu"
        """Female voice for Chinese (Mandarin) (Free voice)"""
        ZHIYU_2 = "Zhiyu_2"
        """Female voice for Chinese (Mandarin) (Free voice)"""

    class CHINESE_MANDARIN_SIMPLIFIED(str, Enum):
        XIAOCHEN = "Xiaochen"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOCHEN_2 = "Xiaochen_2"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOCHEN_3 = "Xiaochen_3"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOCHEN_4 = "Xiaochen_4"
        """Female voice for Chinese (Mandarin, Simplified) (Paid voice)"""
        XIAOHAN = "Xiaohan"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOHAN_2 = "Xiaohan_2"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOMENG = "Xiaomeng"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOMO = "Xiaomo"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOQIU = "Xiaoqiu"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOROU = "Xiaorou"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAORUI = "Xiaorui"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOSHUANG = "Xiaoshuang"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOSHUANG_2 = "Xiaoshuang_2"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOSHUANG_3 = "Xiaoshuang_3"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOXIAO = "Xiaoxiao"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOXIAO_2 = "Xiaoxiao_2"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOXIAO_3 = "Xiaoxiao_3"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOXIAO_4 = "Xiaoxiao_4"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOXIAO_5 = "Xiaoxiao_5"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOYAN = "Xiaoyan"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOYI = "Xiaoyi"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOYI_2 = "Xiaoyi_2"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOYOU = "Xiaoyou"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOYOU_2 = "Xiaoyou_2"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOYOU_3 = "Xiaoyou_3"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOYU = "Xiaoyu"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOYU_2 = "Xiaoyu_2"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        XIAOZHEN = "Xiaozhen"
        """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNFAN = "Yunfan"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNFAN_2 = "Yunfan_2"
        """Male voice for Chinese (Mandarin, Simplified) (Paid voice)"""
        YUNFENG = "Yunfeng"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNHAN = "Yunhan"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNHAO = "Yunhao"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNJIAN = "Yunjian"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNJIE = "Yunjie"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNXI = "Yunxi"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNXI_2 = "Yunxi_2"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNXIA = "Yunxia"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNXIA_2 = "Yunxia_2"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNXIAO = "Yunxiao"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNXIAO_2 = "Yunxiao_2"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNYANG = "Yunyang"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNYE = "Yunye"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNYE_2 = "Yunye_2"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNYI = "Yunyi"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNYI_2 = "Yunyi_2"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
        YUNZE = "Yunze"
        """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""

    class CHINESE_TAIWANESE_MANDARIN_TRADITIONAL(str, Enum):
        HSIAOCHEN = "HsiaoChen"
        """Female voice for Chinese (Taiwanese Mandarin, Traditional) (Free voice)"""
        HSIAOYU = "HsiaoYu"
        """Female voice for Chinese (Taiwanese Mandarin, Traditional) (Free voice)"""
        YUNJHE = "YunJhe"
        """Male voice for Chinese (Taiwanese Mandarin, Traditional) (Free voice)"""

    class CHINESE_WU_SIMPLIFIED(str, Enum):
        XIAOTONG = "Xiaotong"
        """Female voice for Chinese (Wu, Simplified) (Free voice)"""
        YUNZHE = "Yunzhe"
        """Male voice for Chinese (Wu, Simplified) (Free voice)"""

    class CHINESE_ZHONGYUAN_MANDARIN_HENAN_SIMPLIFIED(str, Enum):
        YUNDENG = "Yundeng"
        """Male voice for Chinese (Zhongyuan Mandarin Henan, Simplified) (Free voice)"""

    class CROATIAN_CROATIA(str, Enum):
        GABRIJELA = "Gabrijela"
        """Female voice for Croatian (Croatia) (Free voice)"""
        SRECKO = "Srecko"
        """Male voice for Croatian (Croatia) (Free voice)"""

    class CZECH_CZECHIA(str, Enum):
        ANTONIN = "Antonin"
        """Male voice for Czech (Czechia) (Free voice)"""
        JITKA = "Jitka"
        """Female voice for Czech (Czechia) (Free voice)"""
        VLASTA = "Vlasta"
        """Female voice for Czech (Czechia) (Free voice)"""

    class DANISH_DENMARK(str, Enum):
        CHRISTEL = "Christel"
        """Female voice for Danish (Denmark) (Free voice)"""
        JEPPE = "Jeppe"
        """Male voice for Danish (Denmark) (Free voice)"""
        MADS = "Mads"
        """Male voice for Danish (Denmark) (Free voice)"""
        NAJA = "Naja"
        """Female voice for Danish (Denmark) (Free voice)"""
        SOFFIE = "Soffie"
        """Female voice for Danish (Denmark) (Free voice)"""

    class DUTCH_BELGIUM(str, Enum):
        ARNAUD = "Arnaud"
        """Male voice for Dutch (Belgium) (Free voice)"""
        DENA = "Dena"
        """Female voice for Dutch (Belgium) (Free voice)"""
        LISA = "Lisa"
        """Female voice for Dutch (Belgium) (Free voice)"""
        LISA_2 = "Lisa_2"
        """Female voice for Dutch (Belgium) (Paid voice)"""

    class DUTCH_NETHERLANDS(str, Enum):
        COLETTE = "Colette"
        """Female voice for Dutch (Netherlands) (Free voice)"""
        FENNA = "Fenna"
        """Female voice for Dutch (Netherlands) (Free voice)"""
        LAURA = "Laura"
        """Female voice for Dutch (Netherlands) (Free voice)"""
        LAURA_2 = "Laura_2"
        """Female voice for Dutch (Netherlands) (Paid voice)"""
        LOTTE = "Lotte"
        """Female voice for Dutch (Netherlands) (Free voice)"""
        MAARTEN = "Maarten"
        """Male voice for Dutch (Netherlands) (Free voice)"""
        RUBEN = "Ruben"
        """Male voice for Dutch (Netherlands) (Free voice)"""

    class ENGLISH_AUSTRALIA(str, Enum):
        ANNETTE = "Annette"
        """Female voice for English (Australia) (Free voice)"""
        CARLY = "Carly"
        """Female voice for English (Australia) (Free voice)"""
        DARREN = "Darren"
        """Male voice for English (Australia) (Free voice)"""
        DUNCAN = "Duncan"
        """Male voice for English (Australia) (Free voice)"""
        ELSIE = "Elsie"
        """Female voice for English (Australia) (Free voice)"""
        FREYA = "Freya"
        """Female voice for English (Australia) (Free voice)"""
        JOANNE = "Joanne"
        """Female voice for English (Australia) (Free voice)"""
        KEN = "Ken"
        """Male voice for English (Australia) (Free voice)"""
        KIM = "Kim"
        """Female voice for English (Australia) (Free voice)"""
        LIVIA = "Livia"
        """Female voice for English (Australia) (Free voice)"""
        LIVIA_2 = "Livia_2"
        """Female voice for English (Australia) (Paid voice)"""
        NATASHA = "Natasha"
        """Female voice for English (Australia) (Free voice)"""
        NEIL = "Neil"
        """Male voice for English (Australia) (Free voice)"""
        NICOLE = "Nicole"
        """Female voice for English (Australia) (Free voice)"""
        RUSSELL = "Russell"
        """Male voice for English (Australia) (Free voice)"""
        TIM = "Tim"
        """Male voice for English (Australia) (Free voice)"""
        TINA = "Tina"
        """Female voice for English (Australia) (Free voice)"""
        WILLIAM = "William"
        """Male voice for English (Australia) (Free voice)"""
        WILLIAM_2 = "William_2"
        """Male voice for English (Australia) (Free voice)"""

    class ENGLISH_CANADA(str, Enum):
        CLARA = "Clara"
        """Female voice for English (Canada) (Free voice)"""
        LIAM = "Liam"
        """Male voice for English (Canada) (Free voice)"""

    class ENGLISH_HONG_KONG_SAR(str, Enum):
        SAM = "Sam"
        """Male voice for English (Hong Kong SAR) (Free voice)"""
        YAN = "Yan"
        """Female voice for English (Hong Kong SAR) (Free voice)"""

    class ENGLISH_INDIA(str, Enum):
        AARAV_2 = "Aarav_2"
        """Male voice for English (India) (Free voice)"""
        AARTI_2 = "Aarti_2"
        """Female voice for English (India) (Free voice)"""
        AARTI_3 = "Aarti_3"
        """Female voice for English (India) (Free voice)"""
        AASHI = "Aashi"
        """Female voice for English (India) (Free voice)"""
        ADITI = "Aditi"
        """Female voice for English (India) (Free voice)"""
        ANANYA_2 = "Ananya_2"
        """Female voice for English (India) (Free voice)"""
        ARJUN = "Arjun"
        """Male voice for English (India) (Free voice)"""
        ARJUN_2 = "Arjun_2"
        """Male voice for English (India) (Free voice)"""
        KAJAL = "Kajal"
        """Female voice for English (India) (Free voice)"""
        KAJAL_2 = "Kajal_2"
        """Female voice for English (India) (Paid voice)"""
        KAVYA_2 = "Kavya_2"
        """Female voice for English (India) (Free voice)"""
        KUNAL_2 = "Kunal_2"
        """Male voice for English (India) (Free voice)"""
        NEERJA = "Neerja"
        """Female voice for English (India) (Free voice)"""
        NEERJA_2 = "Neerja_2"
        """Female voice for English (India) (Free voice)"""
        PRABHAT = "Prabhat"
        """Male voice for English (India) (Free voice)"""
        PRABHAT_2 = "Prabhat_2"
        """Male voice for English (India) (Free voice)"""
        RAVEENA = "Raveena"
        """Female voice for English (India) (Free voice)"""
        REHAAN_2 = "Rehaan_2"
        """Male voice for English (India) (Free voice)"""

    class ENGLISH_IRELAND(str, Enum):
        CONNOR = "Connor"
        """Male voice for English (Ireland) (Free voice)"""
        EMILY = "Emily"
        """Female voice for English (Ireland) (Free voice)"""
        NIAMH = "Niamh"
        """Female voice for English (Ireland) (Free voice)"""
        NIAMH_2 = "Niamh_2"
        """Female voice for English (Ireland) (Paid voice)"""

    class ENGLISH_KENYA(str, Enum):
        ASILIA = "Asilia"
        """Female voice for English (Kenya) (Free voice)"""
        CHILEMBA = "Chilemba"
        """Male voice for English (Kenya) (Free voice)"""

    class ENGLISH_NEW_ZEALAND(str, Enum):
        ARYA = "Arya"
        """Female voice for English (New Zealand) (Free voice)"""
        ARYA_2 = "Arya_2"
        """Female voice for English (New Zealand) (Paid voice)"""
        MITCHELL = "Mitchell"
        """Male voice for English (New Zealand) (Free voice)"""
        MOLLY = "Molly"
        """Female voice for English (New Zealand) (Free voice)"""

    class ENGLISH_NIGERIA(str, Enum):
        ABEO = "Abeo"
        """Male voice for English (Nigeria) (Free voice)"""
        EZINNE = "Ezinne"
        """Female voice for English (Nigeria) (Free voice)"""

    class ENGLISH_PHILIPPINES(str, Enum):
        JAMES = "James"
        """Male voice for English (Philippines) (Free voice)"""
        ROSA = "Rosa"
        """Female voice for English (Philippines) (Free voice)"""

    class ENGLISH_SINGAPORE(str, Enum):
        JASMINE = "Jasmine"
        """Female voice for English (Singapore) (Free voice)"""
        JASMINE_2 = "Jasmine_2"
        """Female voice for English (Singapore) (Paid voice)"""
        LUNA = "Luna"
        """Female voice for English (Singapore) (Free voice)"""
        WAYNE = "Wayne"
        """Male voice for English (Singapore) (Free voice)"""

    class ENGLISH_SOUTH_AFRICA(str, Enum):
        AYANDA = "Ayanda"
        """Female voice for English (South Africa) (Free voice)"""
        AYANDA_2 = "Ayanda_2"
        """Female voice for English (South Africa) (Paid voice)"""
        LEAH = "Leah"
        """Female voice for English (South Africa) (Free voice)"""
        LUKE = "Luke"
        """Male voice for English (South Africa) (Free voice)"""

    class ENGLISH_TANZANIA(str, Enum):
        ELIMU = "Elimu"
        """Male voice for English (Tanzania) (Free voice)"""
        IMANI = "Imani"
        """Female voice for English (Tanzania) (Free voice)"""

    class ENGLISH_UNITED_KINGDOM(str, Enum):
        ABBI = "Abbi"
        """Female voice for English (United Kingdom) (Free voice)"""
        ADA = "Ada"
        """Female voice for English (United Kingdom) (Free voice)"""
        ADA_2 = "Ada_2"
        """Female voice for English (United Kingdom) (Paid voice)"""
        ALFIE = "Alfie"
        """Male voice for English (United Kingdom) (Free voice)"""
        AMY = "Amy"
        """Female voice for English (United Kingdom) (Free voice)"""
        AMY_2 = "Amy_2"
        """Female voice for English (United Kingdom) (Free voice)"""
        AMY_3 = "Amy_3"
        """Female voice for English (United Kingdom) (Paid voice)"""
        ARTHUR = "Arthur"
        """Male voice for English (United Kingdom) (Free voice)"""
        BELLA = "Bella"
        """Female voice for English (United Kingdom) (Free voice)"""
        BRYAN = "Bryan"
        """Male voice for English (United Kingdom) (Free voice)"""
        BRYAN_2 = "Bryan_2"
        """Male voice for English (United Kingdom) (Free voice)"""
        BRYAN_3 = "Bryan_3"
        """Male voice for English (United Kingdom) (Paid voice)"""
        ELLIOT = "Elliot"
        """Male voice for English (United Kingdom) (Free voice)"""
        ETHAN = "Ethan"
        """Male voice for English (United Kingdom) (Free voice)"""
        GEMMA = "Gemma"
        """Female voice for English (United Kingdom) (Free voice)"""
        GEMMA_2 = "Gemma_2"
        """Female voice for English (United Kingdom) (Free voice)"""
        HOLLIE = "Hollie"
        """Female voice for English (United Kingdom) (Free voice)"""
        LIBBY = "Libby"
        """Female voice for English (United Kingdom) (Free voice)"""
        MAISIE = "Maisie"
        """Female voice for English (United Kingdom) (Free voice)"""
        NOAH = "Noah"
        """Male voice for English (United Kingdom) (Free voice)"""
        OLIVER = "Oliver"
        """Male voice for English (United Kingdom) (Free voice)"""
        OLIVIA = "Olivia"
        """Female voice for English (United Kingdom) (Free voice)"""
        OLLIE = "Ollie"
        """Male voice for English (United Kingdom) (Free voice)"""
        OLLIE_2 = "Ollie_2"
        """Male voice for English (United Kingdom) (Paid voice)"""
        RYAN_2 = "Ryan_2"
        """Male voice for English (United Kingdom) (Free voice)"""
        SONIA = "Sonia"
        """Female voice for English (United Kingdom) (Free voice)"""
        THOMAS = "Thomas"
        """Male voice for English (United Kingdom) (Free voice)"""

    class ENGLISH_UNITED_STATES(str, Enum):
        ADAM = "Adam"
        """Male voice for English (United States) (Free voice)"""
        ADAM_2 = "Adam_2"
        """Male voice for English (United States) (Paid voice)"""
        ALLOY = "Alloy"
        """Male voice for English (United States) (Free voice)"""
        ALLOY_2 = "Alloy_2"
        """Male voice for English (United States) (Paid voice)"""
        AMANDA = "Amanda"
        """Female voice for English (United States) (Free voice)"""
        AMBER = "Amber"
        """Female voice for English (United States) (Free voice)"""
        ANA = "Ana"
        """Female voice for English (United States) (Free voice)"""
        ANDREW = "Andrew"
        """Male voice for English (United States) (Free voice)"""
        ANDREW_2 = "Andrew_2"
        """Male voice for English (United States) (Free voice)"""
        ANDREW_3 = "Andrew_3"
        """Male voice for English (United States) (Paid voice)"""
        ANDREW_4 = "Andrew_4"
        """Male voice for English (United States) (Paid voice)"""
        ARIA = "Aria"
        """Female voice for English (United States) (Free voice)"""
        ARIA_2 = "Aria_2"
        """Female voice for English (United States) (Paid voice)"""
        ASHLEY = "Ashley"
        """Female voice for English (United States) (Free voice)"""
        AVA = "Ava"
        """Female voice for English (United States) (Free voice)"""
        AVA_2 = "Ava_2"
        """Female voice for English (United States) (Free voice)"""
        AVA_3 = "Ava_3"
        """Female voice for English (United States) (Paid voice)"""
        BRANDON = "Brandon"
        """Male voice for English (United States) (Free voice)"""
        BRANDON_2 = "Brandon_2"
        """Male voice for English (United States) (Free voice)"""
        BREE = "Bree"
        """Female voice for English (United States) (Paid voice)"""
        BRIAN = "Brian"
        """Male voice for English (United States) (Free voice)"""
        BRIAN_2 = "Brian_2"
        """Male voice for English (United States) (Free voice)"""
        BRIAN_3 = "Brian_3"
        """Male voice for English (United States) (Paid voice)"""
        CHRISTOPHER = "Christopher"
        """Male voice for English (United States) (Free voice)"""
        CHRISTOPHER_2 = "Christopher_2"
        """Male voice for English (United States) (Free voice)"""
        CORA = "Cora"
        """Female voice for English (United States) (Free voice)"""
        CORA_2 = "Cora_2"
        """Female voice for English (United States) (Free voice)"""
        DANIELLE = "Danielle"
        """Female voice for English (United States) (Free voice)"""
        DANIELLE_2 = "Danielle_2"
        """Female voice for English (United States) (Paid voice)"""
        DAVIS = "Davis"
        """Male voice for English (United States) (Free voice)"""
        DAVIS_2 = "Davis_2"
        """Male voice for English (United States) (Free voice)"""
        DAVIS_3 = "Davis_3"
        """Male voice for English (United States) (Paid voice)"""
        DEREK = "Derek"
        """Male voice for English (United States) (Free voice)"""
        DUSTIN = "Dustin"
        """Male voice for English (United States) (Free voice)"""
        ECHO = "Echo"
        """Male voice for English (United States) (Free voice)"""
        ELIZABETH = "Elizabeth"
        """Female voice for English (United States) (Free voice)"""
        EMMA = "Emma"
        """Female voice for English (United States) (Free voice)"""
        EMMA_2 = "Emma_2"
        """Female voice for English (United States) (Free voice)"""
        EMMA_3 = "Emma_3"
        """Female voice for English (United States) (Paid voice)"""
        EMMA_4 = "Emma_4"
        """Female voice for English (United States) (Paid voice)"""
        ERIC = "Eric"
        """Male voice for English (United States) (Free voice)"""
        EVELYN = "Evelyn"
        """Female voice for English (United States) (Free voice)"""
        FABLE = "Fable"
        """Neutral voice for English (United States) (Free voice)"""
        GREGORY = "Gregory"
        """Male voice for English (United States) (Free voice)"""
        GUY = "Guy"
        """Male voice for English (United States) (Free voice)"""
        IVY = "Ivy"
        """Female voice for English (United States) (Free voice)"""
        IVY_2 = "Ivy_2"
        """Female voice for English (United States) (Free voice)"""
        JACOB = "Jacob"
        """Male voice for English (United States) (Free voice)"""
        JANE = "Jane"
        """Female voice for English (United States) (Free voice)"""
        JANE_2 = "Jane_2"
        """Female voice for English (United States) (Paid voice)"""
        JASON = "Jason"
        """Male voice for English (United States) (Free voice)"""
        JENNY = "Jenny"
        """Female voice for English (United States) (Free voice)"""
        JENNY_2 = "Jenny_2"
        """Female voice for English (United States) (Free voice)"""
        JENNY_3 = "Jenny_3"
        """Female voice for English (United States) (Paid voice)"""
        JIMMIE = "Jimmie"
        """Male voice for English (United States) (Free voice)"""
        JOANNA = "Joanna"
        """Female voice for English (United States) (Free voice)"""
        JOANNA_2 = "Joanna_2"
        """Female voice for English (United States) (Free voice)"""
        JOANNA_3 = "Joanna_3"
        """Female voice for English (United States) (Paid voice)"""
        JOEY = "Joey"
        """Male voice for English (United States) (Free voice)"""
        JOEY_2 = "Joey_2"
        """Male voice for English (United States) (Free voice)"""
        JUSTIN = "Justin"
        """Male voice for English (United States) (Free voice)"""
        JUSTIN_2 = "Justin_2"
        """Male voice for English (United States) (Free voice)"""
        KAI = "Kai"
        """Male voice for English (United States) (Free voice)"""
        KENDRA = "Kendra"
        """Female voice for English (United States) (Free voice)"""
        KENDRA_2 = "Kendra_2"
        """Female voice for English (United States) (Free voice)"""
        KEVIN = "Kevin"
        """Male voice for English (United States) (Free voice)"""
        KIMBERLY = "Kimberly"
        """Female voice for English (United States) (Free voice)"""
        KIMBERLY_2 = "Kimberly_2"
        """Female voice for English (United States) (Free voice)"""
        LEWIS = "Lewis"
        """Male voice for English (United States) (Free voice)"""
        LOLA = "Lola"
        """Female voice for English (United States) (Free voice)"""
        LUNA_2 = "Luna_2"
        """Female voice for English (United States) (Free voice)"""
        MATTHEW = "Matthew"
        """Male voice for English (United States) (Free voice)"""
        MATTHEW_2 = "Matthew_2"
        """Male voice for English (United States) (Free voice)"""
        MATTHEW_3 = "Matthew_3"
        """Male voice for English (United States) (Paid voice)"""
        MICHELLE = "Michelle"
        """Female voice for English (United States) (Free voice)"""
        MONICA = "Monica"
        """Female voice for English (United States) (Free voice)"""
        NANCY = "Nancy"
        """Female voice for English (United States) (Free voice)"""
        NANCY_2 = "Nancy_2"
        """Female voice for English (United States) (Free voice)"""
        NOVA = "Nova"
        """Female voice for English (United States) (Free voice)"""
        NOVA_2 = "Nova_2"
        """Female voice for English (United States) (Paid voice)"""
        ONYX = "Onyx"
        """Male voice for English (United States) (Free voice)"""
        PHOEBE = "Phoebe"
        """Female voice for English (United States) (Free voice)"""
        PHOEBE_2 = "Phoebe_2"
        """Female voice for English (United States) (Paid voice)"""
        ROGER = "Roger"
        """Male voice for English (United States) (Free voice)"""
        RUTH = "Ruth"
        """Female voice for English (United States) (Free voice)"""
        RUTH_2 = "Ruth_2"
        """Female voice for English (United States) (Paid voice)"""
        RYAN = "Ryan"
        """Male voice for English (United States) (Free voice)"""
        SALLI = "Salli"
        """Female voice for English (United States) (Free voice)"""
        SALLI_2 = "Salli_2"
        """Female voice for English (United States) (Free voice)"""
        SALLI_3 = "Salli_3"
        """Female voice for English (United States) (Paid voice)"""
        SAMUEL = "Samuel"
        """Male voice for English (United States) (Free voice)"""
        SARA = "Sara"
        """Female voice for English (United States) (Free voice)"""
        SERENA = "Serena"
        """Female voice for English (United States) (Free voice)"""
        SERENA_2 = "Serena_2"
        """Female voice for English (United States) (Paid voice)"""
        SHIMMER = "Shimmer"
        """Female voice for English (United States) (Free voice)"""
        STEFFAN = "Steffan"
        """Male voice for English (United States) (Free voice)"""
        STEFFAN_2 = "Steffan_2"
        """Male voice for English (United States) (Free voice)"""
        STEFFAN_3 = "Steffan_3"
        """Male voice for English (United States) (Paid voice)"""
        STEPHEN = "Stephen"
        """Male voice for English (United States) (Free voice)"""
        STEPHEN_2 = "Stephen_2"
        """Male voice for English (United States) (Paid voice)"""
        TIANA = "Tiana"
        """Female voice for English (United States) (Free voice)"""
        TIFFANY = "Tiffany"
        """Female voice for English (United States) (Paid voice)"""
        TONY = "Tony"
        """Male voice for English (United States) (Free voice)"""
        TYLER = "Tyler"
        """Male voice for English (United States) (Free voice)"""

    class ESTONIAN_ESTONIA(str, Enum):
        ANU = "Anu"
        """Female voice for Estonian (Estonia) (Free voice)"""
        KERT = "Kert"
        """Male voice for Estonian (Estonia) (Free voice)"""

    class FILIPINO_PHILIPPINES(str, Enum):
        ANGELO = "Angelo"
        """Male voice for Filipino (Philippines) (Free voice)"""
        BLESSICA = "Blessica"
        """Female voice for Filipino (Philippines) (Free voice)"""

    class FINNISH_FINLAND(str, Enum):
        HARRI = "Harri"
        """Male voice for Finnish (Finland) (Free voice)"""
        NOORA = "Noora"
        """Female voice for Finnish (Finland) (Free voice)"""
        SELMA = "Selma"
        """Female voice for Finnish (Finland) (Free voice)"""
        SUVI = "Suvi"
        """Female voice for Finnish (Finland) (Free voice)"""

    class FRENCH_BELGIUM(str, Enum):
        CHARLINE = "Charline"
        """Female voice for French (Belgium) (Free voice)"""
        GERARD = "Gerard"
        """Male voice for French (Belgium) (Free voice)"""
        ISABELLE = "Isabelle"
        """Female voice for French (Belgium) (Free voice)"""
        ISABELLE_2 = "Isabelle_2"
        """Female voice for French (Belgium) (Paid voice)"""

    class FRENCH_CANADA(str, Enum):
        ANTOINE = "Antoine"
        """Male voice for French (Canada) (Free voice)"""
        CHANTAL = "Chantal"
        """Female voice for French (Canada) (Free voice)"""
        GABRIELLE = "Gabrielle"
        """Female voice for French (Canada) (Free voice)"""
        GABRIELLE_2 = "Gabrielle_2"
        """Female voice for French (Canada) (Paid voice)"""
        JEAN = "Jean"
        """Male voice for French (Canada) (Free voice)"""
        LIAN = "Lian"
        """Male voice for French (Canada) (Free voice)"""
        LIAN_2 = "Lian_2"
        """Male voice for French (Canada) (Paid voice)"""
        SYLVIE = "Sylvie"
        """Female voice for French (Canada) (Free voice)"""
        SYLVIE_2 = "Sylvie_2"
        """Female voice for French (Canada) (Paid voice)"""
        THIERRY = "Thierry"
        """Male voice for French (Canada) (Free voice)"""
        THIERRY_2 = "Thierry_2"
        """Male voice for French (Canada) (Paid voice)"""

    class FRENCH_FRANCE(str, Enum):
        ALAIN = "Alain"
        """Male voice for French (France) (Free voice)"""
        AMBRE = "Ambre"
        """Female voice for French (France) (Paid voice)"""
        BRIGITTE = "Brigitte"
        """Female voice for French (France) (Free voice)"""
        CELESTE = "Celeste"
        """Female voice for French (France) (Free voice)"""
        CELINE = "Celine"
        """Female voice for French (France) (Free voice)"""
        CELINE_2 = "Celine_2"
        """Female voice for French (France) (Paid voice)"""
        CLAUDE = "Claude"
        """Male voice for French (France) (Free voice)"""
        CORALIE = "Coralie"
        """Female voice for French (France) (Free voice)"""
        DENISE = "Denise"
        """Female voice for French (France) (Free voice)"""
        ELOISE = "Eloise"
        """Female voice for French (France) (Free voice)"""
        FLORIN = "Florin"
        """Male voice for French (France) (Paid voice)"""
        HENRI = "Henri"
        """Male voice for French (France) (Free voice)"""
        JACQUELINE = "Jacqueline"
        """Female voice for French (France) (Free voice)"""
        JEROME = "Jerome"
        """Male voice for French (France) (Free voice)"""
        JOSEPHINE = "Josephine"
        """Female voice for French (France) (Free voice)"""
        LEA = "Lea"
        """Female voice for French (France) (Free voice)"""
        LEA_2 = "Lea_2"
        """Female voice for French (France) (Free voice)"""
        LEA_3 = "Lea_3"
        """Female voice for French (France) (Paid voice)"""
        LUCIEN = "Lucien"
        """Male voice for French (France) (Free voice)"""
        MATHIEU = "Mathieu"
        """Male voice for French (France) (Free voice)"""
        MAURICE = "Maurice"
        """Male voice for French (France) (Free voice)"""
        REMI = "Remi"
        """Male voice for French (France) (Free voice)"""
        REMI_2 = "Remi_2"
        """Male voice for French (France) (Paid voice)"""
        REMY = "Remy"
        """Male voice for French (France) (Free voice)"""
        REMY_2 = "Remy_2"
        """Male voice for French (France) (Paid voice)"""
        VIVIENNE = "Vivienne"
        """Female voice for French (France) (Free voice)"""
        VIVIENNE_2 = "Vivienne_2"
        """Female voice for French (France) (Paid voice)"""
        YVES = "Yves"
        """Male voice for French (France) (Free voice)"""
        YVETTE = "Yvette"
        """Female voice for French (France) (Free voice)"""

    class FRENCH_SWITZERLAND(str, Enum):
        ARIANE = "Ariane"
        """Female voice for French (Switzerland) (Free voice)"""
        FABRICE = "Fabrice"
        """Male voice for French (Switzerland) (Free voice)"""

    class GALICIAN(str, Enum):
        ROI = "Roi"
        """Male voice for Galician (Free voice)"""
        SABELA = "Sabela"
        """Female voice for Galician (Free voice)"""

    class GEORGIAN_GEORGIA(str, Enum):
        EKA = "Eka"
        """Female voice for Georgian (Georgia) (Free voice)"""
        GIORGI = "Giorgi"
        """Male voice for Georgian (Georgia) (Free voice)"""

    class GERMAN_AUSTRIA(str, Enum):
        HANNAH = "Hannah"
        """Female voice for German (Austria) (Free voice)"""
        HANNAH_2 = "Hannah_2"
        """Female voice for German (Austria) (Paid voice)"""
        INGRID = "Ingrid"
        """Female voice for German (Austria) (Free voice)"""
        JONAS = "Jonas"
        """Male voice for German (Austria) (Free voice)"""

    class GERMAN_GERMANY(str, Enum):
        AMALA = "Amala"
        """Female voice for German (Germany) (Free voice)"""
        BERND = "Bernd"
        """Male voice for German (Germany) (Free voice)"""
        CHRISTOPH = "Christoph"
        """Male voice for German (Germany) (Free voice)"""
        CONRAD = "Conrad"
        """Male voice for German (Germany) (Free voice)"""
        DANIEL = "Daniel"
        """Male voice for German (Germany) (Free voice)"""
        DANIEL_2 = "Daniel_2"
        """Male voice for German (Germany) (Paid voice)"""
        ELKE = "Elke"
        """Female voice for German (Germany) (Free voice)"""
        FLORIAN = "Florian"
        """Male voice for German (Germany) (Free voice)"""
        FLORIAN_2 = "Florian_2"
        """Male voice for German (Germany) (Paid voice)"""
        GISELA = "Gisela"
        """Female voice for German (Germany) (Free voice)"""
        HANS = "Hans"
        """Male voice for German (Germany) (Free voice)"""
        KASPER = "Kasper"
        """Male voice for German (Germany) (Free voice)"""
        KATJA = "Katja"
        """Female voice for German (Germany) (Free voice)"""
        KILLIAN = "Killian"
        """Male voice for German (Germany) (Free voice)"""
        KLARISSA = "Klarissa"
        """Female voice for German (Germany) (Free voice)"""
        KLAUS = "Klaus"
        """Male voice for German (Germany) (Free voice)"""
        LENNART = "Lennart"
        """Male voice for German (Germany) (Paid voice)"""
        LOUISA = "Louisa"
        """Female voice for German (Germany) (Free voice)"""
        MAJA = "Maja"
        """Female voice for German (Germany) (Free voice)"""
        MARLENE = "Marlene"
        """Female voice for German (Germany) (Free voice)"""
        RALF = "Ralf"
        """Male voice for German (Germany) (Free voice)"""
        SERAPHINA = "Seraphina"
        """Female voice for German (Germany) (Free voice)"""
        SERAPHINA_2 = "Seraphina_2"
        """Female voice for German (Germany) (Paid voice)"""
        TANJA = "Tanja"
        """Female voice for German (Germany) (Free voice)"""
        VICKI = "Vicki"
        """Female voice for German (Germany) (Free voice)"""
        VICKI_2 = "Vicki_2"
        """Female voice for German (Germany) (Free voice)"""
        VICKI_3 = "Vicki_3"
        """Female voice for German (Germany) (Paid voice)"""

    class GERMAN_SWITZERLAND(str, Enum):
        JAN = "Jan"
        """Male voice for German (Switzerland) (Free voice)"""
        LENI = "Leni"
        """Female voice for German (Switzerland) (Free voice)"""
        SABRINA = "Sabrina"
        """Female voice for German (Switzerland) (Free voice)"""
        SABRINA_2 = "Sabrina_2"
        """Female voice for German (Switzerland) (Paid voice)"""

    class GREEK_GREECE(str, Enum):
        ATHINA = "Athina"
        """Female voice for Greek (Greece) (Free voice)"""
        NESTORAS = "Nestoras"
        """Male voice for Greek (Greece) (Free voice)"""

    class GUJARATI_INDIA(str, Enum):
        DHWANI = "Dhwani"
        """Female voice for Gujarati (India) (Free voice)"""
        NIRANJAN = "Niranjan"
        """Male voice for Gujarati (India) (Free voice)"""

    class HEBREW_ISRAEL(str, Enum):
        AVRI = "Avri"
        """Male voice for Hebrew (Israel) (Free voice)"""
        HILA = "Hila"
        """Female voice for Hebrew (Israel) (Free voice)"""

    class HINDI_INDIA(str, Enum):
        AARAV = "Aarav"
        """Male voice for Hindi (India) (Free voice)"""
        AARTI = "Aarti"
        """Female voice for Hindi (India) (Free voice)"""
        ANANYA = "Ananya"
        """Female voice for Hindi (India) (Free voice)"""
        ARJUN_3 = "Arjun_3"
        """Male voice for Hindi (India) (Free voice)"""
        KAVYA = "Kavya"
        """Female voice for Hindi (India) (Free voice)"""
        KUNAL = "Kunal"
        """Male voice for Hindi (India) (Free voice)"""
        MADHUR = "Madhur"
        """Male voice for Hindi (India) (Free voice)"""
        REHAAN = "Rehaan"
        """Male voice for Hindi (India) (Free voice)"""
        SWARA = "Swara"
        """Female voice for Hindi (India) (Free voice)"""

    class HUNGARIAN_HUNGARY(str, Enum):
        NOEMI = "Noemi"
        """Female voice for Hungarian (Hungary) (Free voice)"""
        TAMAS = "Tamas"
        """Male voice for Hungarian (Hungary) (Free voice)"""

    class ICELANDIC_ICELAND(str, Enum):
        DORA = "Dora"
        """Female voice for Icelandic (Iceland) (Free voice)"""
        GUDRUN = "Gudrun"
        """Female voice for Icelandic (Iceland) (Free voice)"""
        GUNNAR = "Gunnar"
        """Male voice for Icelandic (Iceland) (Free voice)"""
        KARL = "Karl"
        """Male voice for Icelandic (Iceland) (Free voice)"""

    class INDONESIAN_INDONESIA(str, Enum):
        ARDI = "Ardi"
        """Male voice for Indonesian (Indonesia) (Free voice)"""
        GADIS = "Gadis"
        """Female voice for Indonesian (Indonesia) (Free voice)"""

    class INUKTITUT_LATIN_CANADA(str, Enum):
        SIQINIQ_2 = "Siqiniq_2"
        """Female voice for Inuktitut (Latin, Canada) (Free voice)"""
        TAQQIQ_2 = "Taqqiq_2"
        """Male voice for Inuktitut (Latin, Canada) (Free voice)"""

    class INUKTITUT_SYLLABICS_CANADA(str, Enum):
        SIQINIQ = "Siqiniq"
        """Female voice for Inuktitut (Syllabics, Canada) (Free voice)"""
        TAQQIQ = "Taqqiq"
        """Male voice for Inuktitut (Syllabics, Canada) (Free voice)"""

    class IRISH_IRELAND(str, Enum):
        COLM = "Colm"
        """Male voice for Irish (Ireland) (Free voice)"""
        ORLA = "Orla"
        """Female voice for Irish (Ireland) (Free voice)"""

    class ITALIAN_ITALY(str, Enum):
        ADRIANO = "Adriano"
        """Male voice for Italian (Italy) (Free voice)"""
        ALESSIO = "Alessio"
        """Male voice for Italian (Italy) (Free voice)"""
        ALESSIO_2 = "Alessio_2"
        """Male voice for Italian (Italy) (Paid voice)"""
        BEATRICE = "Beatrice"
        """Female voice for Italian (Italy) (Paid voice)"""
        BENIGNO = "Benigno"
        """Male voice for Italian (Italy) (Free voice)"""
        BIANCA = "Bianca"
        """Female voice for Italian (Italy) (Free voice)"""
        BIANCA_2 = "Bianca_2"
        """Female voice for Italian (Italy) (Free voice)"""
        BIANCA_3 = "Bianca_3"
        """Female voice for Italian (Italy) (Paid voice)"""
        CALIMERO = "Calimero"
        """Male voice for Italian (Italy) (Free voice)"""
        CARLA = "Carla"
        """Female voice for Italian (Italy) (Free voice)"""
        CATALDO = "Cataldo"
        """Male voice for Italian (Italy) (Free voice)"""
        DIEGO = "Diego"
        """Male voice for Italian (Italy) (Free voice)"""
        ELSA = "Elsa"
        """Female voice for Italian (Italy) (Free voice)"""
        FABIOLA = "Fabiola"
        """Female voice for Italian (Italy) (Free voice)"""
        FIAMMA = "Fiamma"
        """Female voice for Italian (Italy) (Free voice)"""
        GIANNI = "Gianni"
        """Male voice for Italian (Italy) (Free voice)"""
        GIORGIO = "Giorgio"
        """Male voice for Italian (Italy) (Free voice)"""
        GIUSEPPE = "Giuseppe"
        """Male voice for Italian (Italy) (Free voice)"""
        GIUSEPPE_2 = "Giuseppe_2"
        """Male voice for Italian (Italy) (Free voice)"""
        IMELDA = "Imelda"
        """Female voice for Italian (Italy) (Free voice)"""
        IRMA = "Irma"
        """Female voice for Italian (Italy) (Free voice)"""
        ISABELLA = "Isabella"
        """Female voice for Italian (Italy) (Free voice)"""
        ISABELLA_2 = "Isabella_2"
        """Female voice for Italian (Italy) (Free voice)"""
        ISABELLA_3 = "Isabella_3"
        """Female voice for Italian (Italy) (Paid voice)"""
        LISANDRO = "Lisandro"
        """Male voice for Italian (Italy) (Free voice)"""
        LORENZIO = "Lorenzio"
        """Male voice for Italian (Italy) (Paid voice)"""
        MARCELLO = "Marcello"
        """Male voice for Italian (Italy) (Free voice)"""
        PALMIRA = "Palmira"
        """Female voice for Italian (Italy) (Free voice)"""
        PIERINA = "Pierina"
        """Female voice for Italian (Italy) (Free voice)"""
        RINALDO = "Rinaldo"
        """Male voice for Italian (Italy) (Free voice)"""

    class JAPANESE_JAPAN(str, Enum):
        AOI = "Aoi"
        """Female voice for Japanese (Japan) (Free voice)"""
        DAICHI = "Daichi"
        """Male voice for Japanese (Japan) (Free voice)"""
        KAZUHA = "Kazuha"
        """Female voice for Japanese (Japan) (Free voice)"""
        KEITA = "Keita"
        """Male voice for Japanese (Japan) (Free voice)"""
        MASARU = "Masaru"
        """Male voice for Japanese (Japan) (Paid voice)"""
        MAYU = "Mayu"
        """Female voice for Japanese (Japan) (Free voice)"""
        MIZUKI = "Mizuki"
        """Female voice for Japanese (Japan) (Free voice)"""
        NANAMI = "Nanami"
        """Female voice for Japanese (Japan) (Free voice)"""
        NANAMI_2 = "Nanami_2"
        """Female voice for Japanese (Japan) (Paid voice)"""
        NAOKI = "Naoki"
        """Male voice for Japanese (Japan) (Free voice)"""
        SHIORI = "Shiori"
        """Female voice for Japanese (Japan) (Free voice)"""
        TAKUMI = "Takumi"
        """Male voice for Japanese (Japan) (Free voice)"""
        TAKUMI_2 = "Takumi_2"
        """Male voice for Japanese (Japan) (Free voice)"""
        TOMOKO = "Tomoko"
        """Female voice for Japanese (Japan) (Free voice)"""

    class JAVANESE_LATIN_INDONESIA(str, Enum):
        DIMAS = "Dimas"
        """Male voice for Javanese (Latin, Indonesia) (Free voice)"""
        SITI = "Siti"
        """Female voice for Javanese (Latin, Indonesia) (Free voice)"""

    class KANNADA_INDIA(str, Enum):
        GAGAN = "Gagan"
        """Male voice for Kannada (India) (Free voice)"""
        SAPNA = "Sapna"
        """Female voice for Kannada (India) (Free voice)"""

    class KAZAKH_KAZAKHSTAN(str, Enum):
        AIGUL = "Aigul"
        """Female voice for Kazakh (Kazakhstan) (Free voice)"""
        DAULET = "Daulet"
        """Male voice for Kazakh (Kazakhstan) (Free voice)"""

    class KHMER_CAMBODIA(str, Enum):
        PISETH = "Piseth"
        """Male voice for Khmer (Cambodia) (Free voice)"""
        SREYMOM = "Sreymom"
        """Female voice for Khmer (Cambodia) (Free voice)"""

    class KOREAN_KOREA(str, Enum):
        BONGJIN = "BongJin"
        """Male voice for Korean (Korea) (Free voice)"""
        GOOKMIN = "GookMin"
        """Male voice for Korean (Korea) (Free voice)"""
        HYUNSU = "Hyunsu"
        """Male voice for Korean (Korea) (Free voice)"""
        HYUNSU_2 = "Hyunsu_2"
        """Male voice for Korean (Korea) (Free voice)"""
        HYUNSU_3 = "Hyunsu_3"
        """Male voice for Korean (Korea) (Paid voice)"""
        INJOON = "InJoon"
        """Male voice for Korean (Korea) (Free voice)"""
        JIHYE = "Jihye"
        """Female voice for Korean (Korea) (Free voice)"""
        JIMIN = "JiMin"
        """Female voice for Korean (Korea) (Free voice)"""
        SEOHYEON = "SeoHyeon"
        """Female voice for Korean (Korea) (Free voice)"""
        SEOYEON = "Seoyeon"
        """Female voice for Korean (Korea) (Free voice)"""
        SEOYEON_2 = "Seoyeon_2"
        """Female voice for Korean (Korea) (Free voice)"""
        SEOYEON_3 = "Seoyeon_3"
        """Female voice for Korean (Korea) (Paid voice)"""
        SOONBOK = "SoonBok"
        """Female voice for Korean (Korea) (Free voice)"""
        SUNHI = "SunHi"
        """Female voice for Korean (Korea) (Free voice)"""
        SUNHI_2 = "SunHi_2"
        """Female voice for Korean (Korea) (Paid voice)"""
        YUJIN = "YuJin"
        """Female voice for Korean (Korea) (Free voice)"""

    class LAO_LAOS(str, Enum):
        CHANTHAVONG = "Chanthavong"
        """Male voice for Lao (Laos) (Free voice)"""
        KEOMANY = "Keomany"
        """Female voice for Lao (Laos) (Free voice)"""

    class LATVIAN_LATVIA(str, Enum):
        EVERITA = "Everita"
        """Female voice for Latvian (Latvia) (Free voice)"""
        NILS = "Nils"
        """Male voice for Latvian (Latvia) (Free voice)"""

    class LITHUANIAN_LITHUANIA(str, Enum):
        LEONAS = "Leonas"
        """Male voice for Lithuanian (Lithuania) (Free voice)"""
        ONA = "Ona"
        """Female voice for Lithuanian (Lithuania) (Free voice)"""

    class MACEDONIAN_NORTH_MACEDONIA(str, Enum):
        ALEKSANDAR = "Aleksandar"
        """Male voice for Macedonian (North Macedonia) (Free voice)"""
        MARIJA = "Marija"
        """Female voice for Macedonian (North Macedonia) (Free voice)"""

    class MALAYALAM_INDIA(str, Enum):
        MIDHUN = "Midhun"
        """Male voice for Malayalam (India) (Free voice)"""
        SOBHANA = "Sobhana"
        """Female voice for Malayalam (India) (Free voice)"""

    class MALAY_MALAYSIA(str, Enum):
        OSMAN = "Osman"
        """Male voice for Malay (Malaysia) (Free voice)"""
        YASMIN = "Yasmin"
        """Female voice for Malay (Malaysia) (Free voice)"""

    class MALTESE_MALTA(str, Enum):
        GRACE = "Grace"
        """Female voice for Maltese (Malta) (Free voice)"""
        JOSEPH = "Joseph"
        """Male voice for Maltese (Malta) (Free voice)"""

    class MARATHI_INDIA(str, Enum):
        AAROHI = "Aarohi"
        """Female voice for Marathi (India) (Free voice)"""
        MANOHAR = "Manohar"
        """Male voice for Marathi (India) (Free voice)"""

    class MONGOLIAN_MONGOLIA(str, Enum):
        BATAA = "Bataa"
        """Male voice for Mongolian (Mongolia) (Free voice)"""
        YESUI = "Yesui"
        """Female voice for Mongolian (Mongolia) (Free voice)"""

    class NEPALI_NEPAL(str, Enum):
        HEMKALA = "Hemkala"
        """Female voice for Nepali (Nepal) (Free voice)"""
        SAGAR = "Sagar"
        """Male voice for Nepali (Nepal) (Free voice)"""

    class NORWEGIAN_NORWAY(str, Enum):
        FINN = "Finn"
        """Male voice for Norwegian (Norway) (Free voice)"""
        IDA = "Ida"
        """Female voice for Norwegian (Norway) (Free voice)"""
        ISELIN = "Iselin"
        """Female voice for Norwegian (Norway) (Free voice)"""
        LIV = "Liv"
        """Female voice for Norwegian (Norway) (Free voice)"""
        PERNILLE = "Pernille"
        """Female voice for Norwegian (Norway) (Free voice)"""

    class ODIA_INDIA(str, Enum):
        SUBHASINI = "Subhasini"
        """Female voice for Odia (India) (Free voice)"""
        SUKANT = "Sukant"
        """Male voice for Odia (India) (Free voice)"""

    class PASHTO_AFGHANISTAN(str, Enum):
        GULNAWAZ = "GulNawaz"
        """Male voice for Pashto (Afghanistan) (Free voice)"""
        LATIFA = "Latifa"
        """Female voice for Pashto (Afghanistan) (Free voice)"""

    class PERSIAN_IRAN(str, Enum):
        DILARA = "Dilara"
        """Female voice for Persian (Iran) (Free voice)"""
        FARID = "Farid"
        """Male voice for Persian (Iran) (Free voice)"""

    class POLISH_POLAND(str, Enum):
        AGNIESZKA = "Agnieszka"
        """Female voice for Polish (Poland) (Free voice)"""
        EWA = "Ewa"
        """Female voice for Polish (Poland) (Free voice)"""
        EWA_2 = "Ewa_2"
        """Female voice for Polish (Poland) (Paid voice)"""
        JACEK = "Jacek"
        """Male voice for Polish (Poland) (Free voice)"""
        JANN = "Jann"
        """Male voice for Polish (Poland) (Free voice)"""
        MAREK = "Marek"
        """Male voice for Polish (Poland) (Free voice)"""
        MAYA = "Maya"
        """Female voice for Polish (Poland) (Free voice)"""
        OLA = "Ola"
        """Female voice for Polish (Poland) (Free voice)"""
        OLA_2 = "Ola_2"
        """Female voice for Polish (Poland) (Paid voice)"""
        ZOFIA = "Zofia"
        """Female voice for Polish (Poland) (Free voice)"""

    class PORTUGUESE_BRAZIL(str, Enum):
        ANTONIO = "Antonio"
        """Male voice for Portuguese (Brazil) (Free voice)"""
        BRENDA = "Brenda"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        CAMILLA = "Camilla"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        CAMILLA_2 = "Camilla_2"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        CAMILLA_3 = "Camilla_3"
        """Female voice for Portuguese (Brazil) (Paid voice)"""
        CRISTIANO = "Cristiano"
        """Male voice for Portuguese (Brazil) (Free voice)"""
        DONATO = "Donato"
        """Male voice for Portuguese (Brazil) (Free voice)"""
        ELZA = "Elza"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        FABIO = "Fabio"
        """Male voice for Portuguese (Brazil) (Free voice)"""
        FRANCISCA = "Francisca"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        GIOVANNA = "Giovanna"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        HUMBERTO = "Humberto"
        """Male voice for Portuguese (Brazil) (Free voice)"""
        INES = "Ines"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        INES_2 = "Ines_2"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        JULIO = "Julio"
        """Male voice for Portuguese (Brazil) (Free voice)"""
        LEILA = "Leila"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        LETICIA = "Leticia"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        MACERIO = "Macerio"
        """Male voice for Portuguese (Brazil) (Free voice)"""
        MACERIO_2 = "Macerio_2"
        """Male voice for Portuguese (Brazil) (Paid voice)"""
        MANUELA = "Manuela"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        NICOLAU = "Nicolau"
        """Male voice for Portuguese (Brazil) (Free voice)"""
        RICARDO = "Ricardo"
        """Male voice for Portuguese (Brazil) (Free voice)"""
        THALITA = "Thalita"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        THALITA_2 = "Thalita_2"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        THALITA_3 = "Thalita_3"
        """Female voice for Portuguese (Brazil) (Paid voice)"""
        THIAGO = "Thiago"
        """Male voice for Portuguese (Brazil) (Free voice)"""
        VALERIO = "Valerio"
        """Male voice for Portuguese (Brazil) (Free voice)"""
        VITORIA = "Vitoria"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        VITORIA_2 = "Vitoria_2"
        """Female voice for Portuguese (Brazil) (Free voice)"""
        YARA = "Yara"
        """Female voice for Portuguese (Brazil) (Free voice)"""

    class PORTUGUESE_PORTUGAL(str, Enum):
        DUARTE = "Duarte"
        """Male voice for Portuguese (Portugal) (Free voice)"""
        FERNANDA = "Fernanda"
        """Female voice for Portuguese (Portugal) (Free voice)"""
        RAQUEL = "Raquel"
        """Female voice for Portuguese (Portugal) (Free voice)"""

    class PUNJABI_INDIA(str, Enum):
        OJAS = "Ojas"
        """Male voice for Punjabi (India) (Free voice)"""
        VAANI = "Vaani"
        """Female voice for Punjabi (India) (Free voice)"""

    class ROMANIAN_ROMANIA(str, Enum):
        ALINA = "Alina"
        """Female voice for Romanian (Romania) (Free voice)"""
        CARMEN = "Carmen"
        """Female voice for Romanian (Romania) (Free voice)"""
        EMIL = "Emil"
        """Male voice for Romanian (Romania) (Free voice)"""

    class RUSSIAN_RUSSIA(str, Enum):
        DARIYA = "Dariya"
        """Female voice for Russian (Russia) (Free voice)"""
        DMITRY = "Dmitry"
        """Male voice for Russian (Russia) (Free voice)"""
        MAXIM = "Maxim"
        """Male voice for Russian (Russia) (Free voice)"""
        SVETLANA = "Svetlana"
        """Female voice for Russian (Russia) (Free voice)"""
        TATYANA = "Tatyana"
        """Female voice for Russian (Russia) (Free voice)"""

    class SERBIAN_CYRILLIC_SERBIA(str, Enum):
        NICHOLAS = "Nicholas"
        """Male voice for Serbian (Cyrillic, Serbia) (Free voice)"""
        SOPHIE = "Sophie"
        """Female voice for Serbian (Cyrillic, Serbia) (Free voice)"""

    class SERBIAN_LATIN_SERBIA(str, Enum):
        NICHOLAS_2 = "Nicholas_2"
        """Male voice for Serbian (Latin, Serbia) (Free voice)"""
        SOPHIE_2 = "Sophie_2"
        """Female voice for Serbian (Latin, Serbia) (Free voice)"""

    class SINHALA_SRI_LANKA(str, Enum):
        SAMEERA = "Sameera"
        """Male voice for Sinhala (Sri Lanka) (Free voice)"""
        THILINI = "Thilini"
        """Female voice for Sinhala (Sri Lanka) (Free voice)"""

    class SLOVAK_SLOVAKIA(str, Enum):
        LUKAS = "Lukas"
        """Male voice for Slovak (Slovakia) (Free voice)"""
        VIKTORIA = "Viktoria"
        """Female voice for Slovak (Slovakia) (Free voice)"""

    class SLOVENIAN_SLOVENIA(str, Enum):
        PETRA = "Petra"
        """Female voice for Slovenian (Slovenia) (Free voice)"""
        ROK = "Rok"
        """Male voice for Slovenian (Slovenia) (Free voice)"""

    class SOMALI_SOMALIA(str, Enum):
        MUUSE = "Muuse"
        """Male voice for Somali (Somalia) (Free voice)"""
        UBAX = "Ubax"
        """Female voice for Somali (Somalia) (Free voice)"""

    class SPANISH_ARGENTINA(str, Enum):
        ELENA = "Elena"
        """Female voice for Spanish (Argentina) (Free voice)"""
        TOMAS = "Tomas"
        """Male voice for Spanish (Argentina) (Free voice)"""

    class SPANISH_BOLIVIA(str, Enum):
        MARCELO = "Marcelo"
        """Male voice for Spanish (Bolivia) (Free voice)"""
        SOFIA = "Sofia"
        """Female voice for Spanish (Bolivia) (Free voice)"""

    class SPANISH_CASTILIAN(str, Enum):
        CONCHITA = "Conchita"
        """Female voice for Spanish (Castilian) (Free voice)"""
        ENRIQUE = "Enrique"
        """Male voice for Spanish (Castilian) (Free voice)"""
        LUCIA = "Lucia"
        """Female voice for Spanish (Castilian) (Free voice)"""
        LUCIA_2 = "Lucia_2"
        """Female voice for Spanish (Castilian) (Free voice)"""
        LUCIA_3 = "Lucia_3"
        """Female voice for Spanish (Castilian) (Paid voice)"""
        SERGIO = "Sergio"
        """Male voice for Spanish (Castilian) (Free voice)"""
        SERGIO_2 = "Sergio_2"
        """Male voice for Spanish (Castilian) (Paid voice)"""

    class SPANISH_CHILE(str, Enum):
        CATALINA = "Catalina"
        """Female voice for Spanish (Chile) (Free voice)"""
        LORENZO = "Lorenzo"
        """Male voice for Spanish (Chile) (Free voice)"""

    class SPANISH_COLOMBIA(str, Enum):
        GONZALO = "Gonzalo"
        """Male voice for Spanish (Colombia) (Free voice)"""
        SALOME = "Salome"
        """Female voice for Spanish (Colombia) (Free voice)"""

    class SPANISH_COSTA_RICA(str, Enum):
        JUAN = "Juan"
        """Male voice for Spanish (Costa Rica) (Free voice)"""
        MARIA = "Maria"
        """Female voice for Spanish (Costa Rica) (Free voice)"""

    class SPANISH_CUBA(str, Enum):
        BELKYS = "Belkys"
        """Female voice for Spanish (Cuba) (Free voice)"""
        MANUEL = "Manuel"
        """Male voice for Spanish (Cuba) (Free voice)"""

    class SPANISH_DOMINICAN_REPUBLIC(str, Enum):
        EMILIO = "Emilio"
        """Male voice for Spanish (Dominican Republic) (Free voice)"""
        RAMONA = "Ramona"
        """Female voice for Spanish (Dominican Republic) (Free voice)"""

    class SPANISH_ECUADOR(str, Enum):
        ANDREA = "Andrea"
        """Female voice for Spanish (Ecuador) (Free voice)"""
        LUIS = "Luis"
        """Male voice for Spanish (Ecuador) (Free voice)"""

    class SPANISH_EL_SALVADOR(str, Enum):
        LORENA = "Lorena"
        """Female voice for Spanish (El Salvador) (Free voice)"""
        RODRIGO = "Rodrigo"
        """Male voice for Spanish (El Salvador) (Free voice)"""

    class SPANISH_EQUATORIAL_GUINEA(str, Enum):
        JAVIER = "Javier"
        """Male voice for Spanish (Equatorial Guinea) (Free voice)"""
        TERESA = "Teresa"
        """Female voice for Spanish (Equatorial Guinea) (Free voice)"""

    class SPANISH_GUATEMALA(str, Enum):
        ANDRES = "Andres"
        """Male voice for Spanish (Guatemala) (Free voice)"""
        MARTA = "Marta"
        """Female voice for Spanish (Guatemala) (Free voice)"""

    class SPANISH_HONDURAS(str, Enum):
        CARLOS = "Carlos"
        """Male voice for Spanish (Honduras) (Free voice)"""
        KARLA = "Karla"
        """Female voice for Spanish (Honduras) (Free voice)"""

    class SPANISH_MEXICO(str, Enum):
        ANDRE = "Andre"
        """Male voice for Spanish (Mexico) (Free voice)"""
        ANDRE_2 = "Andre_2"
        """Male voice for Spanish (Mexico) (Paid voice)"""
        BEATRIZ = "Beatriz"
        """Female voice for Spanish (Mexico) (Free voice)"""
        CANDELA = "Candela"
        """Female voice for Spanish (Mexico) (Free voice)"""
        CARLOTA = "Carlota"
        """Female voice for Spanish (Mexico) (Free voice)"""
        CECILIO = "Cecilio"
        """Male voice for Spanish (Mexico) (Free voice)"""
        DALIA = "Dalia"
        """Female voice for Spanish (Mexico) (Free voice)"""
        DALIA_2 = "Dalia_2"
        """Female voice for Spanish (Mexico) (Free voice)"""
        GERARDO = "Gerardo"
        """Male voice for Spanish (Mexico) (Free voice)"""
        JORGE = "Jorge"
        """Male voice for Spanish (Mexico) (Free voice)"""
        JORGE_2 = "Jorge_2"
        """Male voice for Spanish (Mexico) (Free voice)"""
        LARISSA = "Larissa"
        """Female voice for Spanish (Mexico) (Free voice)"""
        LIBERTO = "Liberto"
        """Male voice for Spanish (Mexico) (Free voice)"""
        LUCIANO = "Luciano"
        """Male voice for Spanish (Mexico) (Free voice)"""
        MARINA = "Marina"
        """Female voice for Spanish (Mexico) (Free voice)"""
        MIA = "Mia"
        """Female voice for Spanish (Mexico) (Free voice)"""
        MIA_2 = "Mia_2"
        """Female voice for Spanish (Mexico) (Free voice)"""
        MIA_3 = "Mia_3"
        """Female voice for Spanish (Mexico) (Paid voice)"""
        NURIA = "Nuria"
        """Female voice for Spanish (Mexico) (Free voice)"""
        PELAYO = "Pelayo"
        """Male voice for Spanish (Mexico) (Free voice)"""
        RENATA = "Renata"
        """Female voice for Spanish (Mexico) (Free voice)"""
        TRISTAN = "Tristan"
        """Male voice for Spanish (Mexico) (Paid voice)"""
        XIMENA = "Ximena"
        """Female voice for Spanish (Mexico) (Paid voice)"""
        YAGO = "Yago"
        """Male voice for Spanish (Mexico) (Free voice)"""

    class SPANISH_NICARAGUA(str, Enum):
        FEDERICO = "Federico"
        """Male voice for Spanish (Nicaragua) (Free voice)"""
        YOLANDA = "Yolanda"
        """Female voice for Spanish (Nicaragua) (Free voice)"""

    class SPANISH_PANAMA(str, Enum):
        MARGARITA = "Margarita"
        """Female voice for Spanish (Panama) (Free voice)"""
        ROBERTO = "Roberto"
        """Male voice for Spanish (Panama) (Free voice)"""

    class SPANISH_PARAGUAY(str, Enum):
        MARIO = "Mario"
        """Male voice for Spanish (Paraguay) (Free voice)"""
        TANIA = "Tania"
        """Female voice for Spanish (Paraguay) (Free voice)"""

    class SPANISH_PERU(str, Enum):
        ALEX = "Alex"
        """Male voice for Spanish (Peru) (Free voice)"""
        CAMILA = "Camila"
        """Female voice for Spanish (Peru) (Free voice)"""

    class SPANISH_PUERTO_RICO(str, Enum):
        KARINA = "Karina"
        """Female voice for Spanish (Puerto Rico) (Free voice)"""
        VICTOR = "Victor"
        """Male voice for Spanish (Puerto Rico) (Free voice)"""

    class SPANISH_SPAIN(str, Enum):
        ABRIL = "Abril"
        """Female voice for Spanish (Spain) (Free voice)"""
        ALVARO = "Alvaro"
        """Male voice for Spanish (Spain) (Free voice)"""
        ARABELLA = "Arabella"
        """Female voice for Spanish (Spain) (Free voice)"""
        ARNAU = "Arnau"
        """Male voice for Spanish (Spain) (Free voice)"""
        DARIO = "Dario"
        """Male voice for Spanish (Spain) (Free voice)"""
        ELIAS = "Elias"
        """Male voice for Spanish (Spain) (Free voice)"""
        ELVIRA = "Elvira"
        """Female voice for Spanish (Spain) (Free voice)"""
        ESTRELLA = "Estrella"
        """Female voice for Spanish (Spain) (Free voice)"""
        IRENE = "Irene"
        """Female voice for Spanish (Spain) (Free voice)"""
        ISIDORA = "Isidora"
        """Female voice for Spanish (Spain) (Free voice)"""
        LAIA = "Laia"
        """Female voice for Spanish (Spain) (Free voice)"""
        LIA = "Lia"
        """Female voice for Spanish (Spain) (Free voice)"""
        NIL = "Nil"
        """Male voice for Spanish (Spain) (Free voice)"""
        SAUL = "Saul"
        """Male voice for Spanish (Spain) (Free voice)"""
        TEO = "Teo"
        """Male voice for Spanish (Spain) (Free voice)"""
        TRIANA = "Triana"
        """Female voice for Spanish (Spain) (Free voice)"""
        TRISTAN_ES = "Tristan_ES"
        """Male voice for Spanish (Spain) (Free voice)"""
        TRISTAN_ES_2 = "Tristan_ES_2"
        """Male voice for Spanish (Spain) (Paid voice)"""
        VERA = "Vera"
        """Female voice for Spanish (Spain) (Free voice)"""
        XIMENA_ES = "Ximena_ES"
        """Female voice for Spanish (Spain) (Free voice)"""
        XIMENA_ES_2 = "Ximena_ES_2"
        """Female voice for Spanish (Spain) (Free voice)"""
        XIMENA_ES_3 = "Ximena_ES_3"
        """Female voice for Spanish (Spain) (Paid voice)"""

    class SPANISH_UNITED_STATES(str, Enum):
        ALONSO = "Alonso"
        """Male voice for Spanish (United States) (Free voice)"""
        LUPE = "Lupe"
        """Female voice for Spanish (United States) (Free voice)"""
        LUPE_2 = "Lupe_2"
        """Female voice for Spanish (United States) (Free voice)"""
        LUPE_3 = "Lupe_3"
        """Female voice for Spanish (United States) (Paid voice)"""
        MIGUEL = "Miguel"
        """Male voice for Spanish (United States) (Free voice)"""
        PALOMA = "Paloma"
        """Female voice for Spanish (United States) (Free voice)"""
        PEDRO = "Pedro"
        """Male voice for Spanish (United States) (Free voice)"""
        PEDRO_2 = "Pedro_2"
        """Male voice for Spanish (United States) (Paid voice)"""
        PENELOPE = "Penelope"
        """Female voice for Spanish (United States) (Free voice)"""

    class SPANISH_URUGUAY(str, Enum):
        MATEO = "Mateo"
        """Male voice for Spanish (Uruguay) (Free voice)"""
        VALENTINA = "Valentina"
        """Female voice for Spanish (Uruguay) (Free voice)"""

    class SPANISH_VENEZUELA(str, Enum):
        PAOLA = "Paola"
        """Female voice for Spanish (Venezuela) (Free voice)"""
        SEBASTIAN = "Sebastian"
        """Male voice for Spanish (Venezuela) (Free voice)"""

    class SUNDANESE_INDONESIA(str, Enum):
        JAJANG = "Jajang"
        """Male voice for Sundanese (Indonesia) (Free voice)"""
        TUTI = "Tuti"
        """Female voice for Sundanese (Indonesia) (Free voice)"""

    class SWAHILI_KENYA(str, Enum):
        RAFIKI = "Rafiki"
        """Male voice for Swahili (Kenya) (Free voice)"""
        ZURI = "Zuri"
        """Female voice for Swahili (Kenya) (Free voice)"""

    class SWAHILI_TANZANIA(str, Enum):
        DAUDI = "Daudi"
        """Male voice for Swahili (Tanzania) (Free voice)"""
        REHEMA = "Rehema"
        """Female voice for Swahili (Tanzania) (Free voice)"""

    class SWEDISH_SWEDEN(str, Enum):
        ASTRID = "Astrid"
        """Female voice for Swedish (Sweden) (Free voice)"""
        ELIN = "Elin"
        """Female voice for Swedish (Sweden) (Free voice)"""
        HILLEVI = "Hillevi"
        """Female voice for Swedish (Sweden) (Free voice)"""
        MATTIAS = "Mattias"
        """Male voice for Swedish (Sweden) (Free voice)"""
        SOFIE = "Sofie"
        """Female voice for Swedish (Sweden) (Free voice)"""

    class TAMIL_INDIA(str, Enum):
        PALLAVI = "Pallavi"
        """Female voice for Tamil (India) (Free voice)"""
        VALLUVAR = "Valluvar"
        """Male voice for Tamil (India) (Free voice)"""

    class TAMIL_MALAYSIA(str, Enum):
        KANI = "Kani"
        """Female voice for Tamil (Malaysia) (Free voice)"""
        SURYA = "Surya"
        """Male voice for Tamil (Malaysia) (Free voice)"""

    class TAMIL_SINGAPORE(str, Enum):
        ANBU = "Anbu"
        """Male voice for Tamil (Singapore) (Free voice)"""
        VENBA = "Venba"
        """Female voice for Tamil (Singapore) (Free voice)"""

    class TAMIL_SRI_LANKA(str, Enum):
        KUMAR = "Kumar"
        """Male voice for Tamil (Sri Lanka) (Free voice)"""
        SARANYA = "Saranya"
        """Female voice for Tamil (Sri Lanka) (Free voice)"""

    class TELUGU_INDIA(str, Enum):
        MOHAN = "Mohan"
        """Male voice for Telugu (India) (Free voice)"""
        SHRUTI = "Shruti"
        """Female voice for Telugu (India) (Free voice)"""

    class THAI_THAILAND(str, Enum):
        ACHARA = "Achara"
        """Female voice for Thai (Thailand) (Free voice)"""
        NIWAT = "Niwat"
        """Male voice for Thai (Thailand) (Free voice)"""
        PREMWADEE = "Premwadee"
        """Female voice for Thai (Thailand) (Free voice)"""

    class TURKISH_TURKIYE(str, Enum):
        AHMET = "Ahmet"
        """Male voice for Turkish (Türkiye) (Free voice)"""
        BURCU = "Burcu"
        """Female voice for Turkish (Türkiye) (Free voice)"""
        EMEL = "Emel"
        """Female voice for Turkish (Türkiye) (Free voice)"""
        FILIZ = "Filiz"
        """Female voice for Turkish (Türkiye) (Free voice)"""

    class UKRAINIAN_UKRAINE(str, Enum):
        OSTAP = "Ostap"
        """Male voice for Ukrainian (Ukraine) (Free voice)"""
        POLINA = "Polina"
        """Female voice for Ukrainian (Ukraine) (Free voice)"""

    class URDU_INDIA(str, Enum):
        GUL = "Gul"
        """Female voice for Urdu (India) (Free voice)"""
        SALMAN = "Salman"
        """Male voice for Urdu (India) (Free voice)"""

    class URDU_PAKISTAN(str, Enum):
        ASAD = "Asad"
        """Male voice for Urdu (Pakistan) (Free voice)"""
        UZMA = "Uzma"
        """Female voice for Urdu (Pakistan) (Free voice)"""

    class UZBEK_LATIN_UZBEKISTAN(str, Enum):
        MADINA = "Madina"
        """Female voice for Uzbek (Latin, Uzbekistan) (Free voice)"""
        SARDOR = "Sardor"
        """Male voice for Uzbek (Latin, Uzbekistan) (Free voice)"""

    class VIETNAMESE_VIETNAM(str, Enum):
        HOAIMY = "HoaiMy"
        """Female voice for Vietnamese (Vietnam) (Free voice)"""
        NAMMINH = "NamMinh"
        """Male voice for Vietnamese (Vietnam) (Free voice)"""

    class WELSH_UNITED_KINGDOM(str, Enum):
        ALED = "Aled"
        """Male voice for Welsh (United Kingdom) (Free voice)"""
        GERAINT = "Geraint"
        """Male voice for Welsh (United Kingdom) (Free voice)"""
        GWYNETH = "Gwyneth"
        """Female voice for Welsh (United Kingdom) (Free voice)"""
        NIA = "Nia"
        """Female voice for Welsh (United Kingdom) (Free voice)"""

    class ZULU_SOUTH_AFRICA(str, Enum):
        THANDO = "Thando"
        """Female voice for Zulu (South Africa) (Free voice)"""
        THEMBA = "Themba"
        """Male voice for Zulu (South Africa) (Free voice)"""
