from enum import Enum


class VoiceNameEnum(str, Enum):
    AARAV = "Aarav"
    """Male voice for Hindi (India) (Free voice)"""
    AARAV_2 = "Aarav_2"
    """Male voice for English (India) (Free voice)"""
    AAROHI = "Aarohi"
    """Female voice for Marathi (India) (Free voice)"""
    AARTI = "Aarti"
    """Female voice for Hindi (India) (Free voice)"""
    AARTI_2 = "Aarti_2"
    """Female voice for English (India) (Free voice)"""
    AARTI_3 = "Aarti_3"
    """Female voice for English (India) (Free voice)"""
    AASHI = "Aashi"
    """Female voice for English (India) (Free voice)"""
    ABBI = "Abbi"
    """Female voice for English (United Kingdom) (Free voice)"""
    ABDULLAH = "Abdullah"
    """Male voice for Arabic (Oman) (Free voice)"""
    ABEO = "Abeo"
    """Male voice for English (Nigeria) (Free voice)"""
    ABRIL = "Abril"
    """Female voice for Spanish (Spain) (Free voice)"""
    ACHARA = "Achara"
    """Female voice for Thai (Thailand) (Free voice)"""
    ADA = "Ada"
    """Female voice for English (United Kingdom) (Free voice)"""
    ADA_2 = "Ada_2"
    """Female voice for English (United Kingdom) (Paid voice)"""
    ADAM = "Adam"
    """Male voice for English (United States) (Free voice)"""
    ADAM_2 = "Adam_2"
    """Male voice for English (United States) (Paid voice)"""
    ADITI = "Aditi"
    """Female voice for English (India) (Free voice)"""
    ADRI = "Adri"
    """Female voice for Afrikaans (South Africa) (Free voice)"""
    ADRIANO = "Adriano"
    """Male voice for Italian (Italy) (Free voice)"""
    AGNIESZKA = "Agnieszka"
    """Female voice for Polish (Poland) (Free voice)"""
    AHMET = "Ahmet"
    """Male voice for Turkish (Türkiye) (Free voice)"""
    AIGUL = "Aigul"
    """Female voice for Kazakh (Kazakhstan) (Free voice)"""
    AINHOA = "Ainhoa"
    """Female voice for Basque (Free voice)"""
    ALAIN = "Alain"
    """Male voice for French (France) (Free voice)"""
    ALBA = "Alba"
    """Female voice for Catalan (Free voice)"""
    ALED = "Aled"
    """Male voice for Welsh (United Kingdom) (Free voice)"""
    ALEKSANDAR = "Aleksandar"
    """Male voice for Macedonian (North Macedonia) (Free voice)"""
    ALESSIO = "Alessio"
    """Male voice for Italian (Italy) (Free voice)"""
    ALESSIO_2 = "Alessio_2"
    """Male voice for Italian (Italy) (Paid voice)"""
    ALEX = "Alex"
    """Male voice for Spanish (Peru) (Free voice)"""
    ALFIE = "Alfie"
    """Male voice for English (United Kingdom) (Free voice)"""
    ALI = "Ali"
    """Male voice for Arabic (Bahrain) (Free voice)"""
    ALINA = "Alina"
    """Female voice for Romanian (Romania) (Free voice)"""
    ALLOY = "Alloy"
    """Male voice for English (United States) (Free voice)"""
    ALLOY_2 = "Alloy_2"
    """Male voice for English (United States) (Paid voice)"""
    ALONSO = "Alonso"
    """Male voice for Spanish (United States) (Free voice)"""
    ALVARO = "Alvaro"
    """Male voice for Spanish (Spain) (Free voice)"""
    AMAL = "Amal"
    """Female voice for Arabic (Qatar) (Free voice)"""
    AMALA = "Amala"
    """Female voice for German (Germany) (Free voice)"""
    AMANDA = "Amanda"
    """Female voice for English (United States) (Free voice)"""
    AMANY = "Amany"
    """Female voice for Arabic (Syria) (Free voice)"""
    AMBER = "Amber"
    """Female voice for English (United States) (Free voice)"""
    AMBRE = "Ambre"
    """Female voice for French (France) (Paid voice)"""
    AMEHA = "Ameha"
    """Male voice for Amharic (Ethiopia) (Free voice)"""
    AMINA = "Amina"
    """Female voice for Arabic (Algeria) (Free voice)"""
    AMY = "Amy"
    """Female voice for English (United Kingdom) (Free voice)"""
    AMY_2 = "Amy_2"
    """Female voice for English (United Kingdom) (Free voice)"""
    AMY_3 = "Amy_3"
    """Female voice for English (United Kingdom) (Paid voice)"""
    ANA = "Ana"
    """Female voice for English (United States) (Free voice)"""
    ANAHIT = "Anahit"
    """Female voice for Armenian (Armenia) (Free voice)"""
    ANANYA = "Ananya"
    """Female voice for Hindi (India) (Free voice)"""
    ANANYA_2 = "Ananya_2"
    """Female voice for English (India) (Free voice)"""
    ANBU = "Anbu"
    """Male voice for Tamil (Singapore) (Free voice)"""
    ANDER = "Ander"
    """Male voice for Basque (Free voice)"""
    ANDRE = "Andre"
    """Male voice for Spanish (Mexico) (Free voice)"""
    ANDRE_2 = "Andre_2"
    """Male voice for Spanish (Mexico) (Paid voice)"""
    ANDREA = "Andrea"
    """Female voice for Spanish (Ecuador) (Free voice)"""
    ANDRES = "Andres"
    """Male voice for Spanish (Guatemala) (Free voice)"""
    ANDREW = "Andrew"
    """Male voice for English (United States) (Free voice)"""
    ANDREW_2 = "Andrew_2"
    """Male voice for English (United States) (Free voice)"""
    ANDREW_3 = "Andrew_3"
    """Male voice for English (United States) (Paid voice)"""
    ANDREW_4 = "Andrew_4"
    """Male voice for English (United States) (Paid voice)"""
    ANGELO = "Angelo"
    """Male voice for Filipino (Philippines) (Free voice)"""
    ANILA = "Anila"
    """Female voice for Albanian (Albania) (Free voice)"""
    ANNETTE = "Annette"
    """Female voice for English (Australia) (Free voice)"""
    ANTOINE = "Antoine"
    """Male voice for French (Canada) (Free voice)"""
    ANTONIN = "Antonin"
    """Male voice for Czech (Czechia) (Free voice)"""
    ANTONIO = "Antonio"
    """Male voice for Portuguese (Brazil) (Free voice)"""
    ANU = "Anu"
    """Female voice for Estonian (Estonia) (Free voice)"""
    AOI = "Aoi"
    """Female voice for Japanese (Japan) (Free voice)"""
    ARABELLA = "Arabella"
    """Female voice for Spanish (Spain) (Free voice)"""
    ARDI = "Ardi"
    """Male voice for Indonesian (Indonesia) (Free voice)"""
    ARIA = "Aria"
    """Female voice for English (United States) (Free voice)"""
    ARIA_2 = "Aria_2"
    """Female voice for English (United States) (Paid voice)"""
    ARIANE = "Ariane"
    """Female voice for French (Switzerland) (Free voice)"""
    ARJUN = "Arjun"
    """Male voice for English (India) (Free voice)"""
    ARJUN_2 = "Arjun_2"
    """Male voice for English (India) (Free voice)"""
    ARJUN_3 = "Arjun_3"
    """Male voice for Hindi (India) (Free voice)"""
    ARLET = "Arlet"
    """Female voice for Catalan (Free voice)"""
    ARNAU = "Arnau"
    """Male voice for Spanish (Spain) (Free voice)"""
    ARNAUD = "Arnaud"
    """Male voice for Dutch (Belgium) (Free voice)"""
    ARTHUR = "Arthur"
    """Male voice for English (United Kingdom) (Free voice)"""
    ARYA = "Arya"
    """Female voice for English (New Zealand) (Free voice)"""
    ARYA_2 = "Arya_2"
    """Female voice for English (New Zealand) (Paid voice)"""
    ASAD = "Asad"
    """Male voice for Urdu (Pakistan) (Free voice)"""
    ASHLEY = "Ashley"
    """Female voice for English (United States) (Free voice)"""
    ASILIA = "Asilia"
    """Female voice for English (Kenya) (Free voice)"""
    ASTRID = "Astrid"
    """Female voice for Swedish (Sweden) (Free voice)"""
    ATHINA = "Athina"
    """Female voice for Greek (Greece) (Free voice)"""
    AVA = "Ava"
    """Female voice for English (United States) (Free voice)"""
    AVA_2 = "Ava_2"
    """Female voice for English (United States) (Free voice)"""
    AVA_3 = "Ava_3"
    """Female voice for English (United States) (Paid voice)"""
    AVRI = "Avri"
    """Male voice for Hebrew (Israel) (Free voice)"""
    AYANDA = "Ayanda"
    """Female voice for English (South Africa) (Free voice)"""
    AYANDA_2 = "Ayanda_2"
    """Female voice for English (South Africa) (Paid voice)"""
    AYSHA = "Aysha"
    """Female voice for Arabic (Oman) (Free voice)"""
    BABEK = "Babek"
    """Male voice for Azerbaijani (Latin, Azerbaijan) (Free voice)"""
    BANU = "Banu"
    """Female voice for Azerbaijani (Latin, Azerbaijan) (Free voice)"""
    BASHKAR = "Bashkar"
    """Male voice for Bengali (India) (Free voice)"""
    BASSEL = "Bassel"
    """Male voice for Arabic (Iraq) (Free voice)"""
    BATAA = "Bataa"
    """Male voice for Mongolian (Mongolia) (Free voice)"""
    BEATRICE = "Beatrice"
    """Female voice for Italian (Italy) (Paid voice)"""
    BEATRIZ = "Beatriz"
    """Female voice for Spanish (Mexico) (Free voice)"""
    BELKYS = "Belkys"
    """Female voice for Spanish (Cuba) (Free voice)"""
    BELLA = "Bella"
    """Female voice for English (United Kingdom) (Free voice)"""
    BENIGNO = "Benigno"
    """Male voice for Italian (Italy) (Free voice)"""
    BERND = "Bernd"
    """Male voice for German (Germany) (Free voice)"""
    BIANCA = "Bianca"
    """Female voice for Italian (Italy) (Free voice)"""
    BIANCA_2 = "Bianca_2"
    """Female voice for Italian (Italy) (Free voice)"""
    BIANCA_3 = "Bianca_3"
    """Female voice for Italian (Italy) (Paid voice)"""
    BLESSICA = "Blessica"
    """Female voice for Filipino (Philippines) (Free voice)"""
    BONGJIN = "BongJin"
    """Male voice for Korean (Korea) (Free voice)"""
    BORISLAV = "Borislav"
    """Male voice for Bulgarian (Bulgaria) (Free voice)"""
    BRANDON = "Brandon"
    """Male voice for English (United States) (Free voice)"""
    BRANDON_2 = "Brandon_2"
    """Male voice for English (United States) (Free voice)"""
    BREE = "Bree"
    """Female voice for English (United States) (Paid voice)"""
    BRENDA = "Brenda"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    BRIAN = "Brian"
    """Male voice for English (United States) (Free voice)"""
    BRIAN_2 = "Brian_2"
    """Male voice for English (United States) (Free voice)"""
    BRIAN_3 = "Brian_3"
    """Male voice for English (United States) (Paid voice)"""
    BRIGITTE = "Brigitte"
    """Female voice for French (France) (Free voice)"""
    BRYAN = "Bryan"
    """Male voice for English (United Kingdom) (Free voice)"""
    BRYAN_2 = "Bryan_2"
    """Male voice for English (United Kingdom) (Free voice)"""
    BRYAN_3 = "Bryan_3"
    """Male voice for English (United Kingdom) (Paid voice)"""
    BURCU = "Burcu"
    """Female voice for Turkish (Türkiye) (Free voice)"""
    CALIMERO = "Calimero"
    """Male voice for Italian (Italy) (Free voice)"""
    CAMILA = "Camila"
    """Female voice for Spanish (Peru) (Free voice)"""
    CAMILLA = "Camilla"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    CAMILLA_2 = "Camilla_2"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    CAMILLA_3 = "Camilla_3"
    """Female voice for Portuguese (Brazil) (Paid voice)"""
    CANDELA = "Candela"
    """Female voice for Spanish (Mexico) (Free voice)"""
    CARLA = "Carla"
    """Female voice for Italian (Italy) (Free voice)"""
    CARLOS = "Carlos"
    """Male voice for Spanish (Honduras) (Free voice)"""
    CARLOTA = "Carlota"
    """Female voice for Spanish (Mexico) (Free voice)"""
    CARLY = "Carly"
    """Female voice for English (Australia) (Free voice)"""
    CARMEN = "Carmen"
    """Female voice for Romanian (Romania) (Free voice)"""
    CATALDO = "Cataldo"
    """Male voice for Italian (Italy) (Free voice)"""
    CATALINA = "Catalina"
    """Female voice for Spanish (Chile) (Free voice)"""
    CECILIO = "Cecilio"
    """Male voice for Spanish (Mexico) (Free voice)"""
    CELESTE = "Celeste"
    """Female voice for French (France) (Free voice)"""
    CELINE = "Celine"
    """Female voice for French (France) (Free voice)"""
    CELINE_2 = "Celine_2"
    """Female voice for French (France) (Paid voice)"""
    CHANTAL = "Chantal"
    """Female voice for French (Canada) (Free voice)"""
    CHANTHAVONG = "Chanthavong"
    """Male voice for Lao (Laos) (Free voice)"""
    CHARLINE = "Charline"
    """Female voice for French (Belgium) (Free voice)"""
    CHILEMBA = "Chilemba"
    """Male voice for English (Kenya) (Free voice)"""
    CHRISTEL = "Christel"
    """Female voice for Danish (Denmark) (Free voice)"""
    CHRISTOPH = "Christoph"
    """Male voice for German (Germany) (Free voice)"""
    CHRISTOPHER = "Christopher"
    """Male voice for English (United States) (Free voice)"""
    CHRISTOPHER_2 = "Christopher_2"
    """Male voice for English (United States) (Free voice)"""
    CLARA = "Clara"
    """Female voice for English (Canada) (Free voice)"""
    CLAUDE = "Claude"
    """Male voice for French (France) (Free voice)"""
    COLETTE = "Colette"
    """Female voice for Dutch (Netherlands) (Free voice)"""
    COLM = "Colm"
    """Male voice for Irish (Ireland) (Free voice)"""
    CONCHITA = "Conchita"
    """Female voice for Spanish (Castilian) (Free voice)"""
    CONNOR = "Connor"
    """Male voice for English (Ireland) (Free voice)"""
    CONRAD = "Conrad"
    """Male voice for German (Germany) (Free voice)"""
    CORA = "Cora"
    """Female voice for English (United States) (Free voice)"""
    CORA_2 = "Cora_2"
    """Female voice for English (United States) (Free voice)"""
    CORALIE = "Coralie"
    """Female voice for French (France) (Free voice)"""
    CRISTIANO = "Cristiano"
    """Male voice for Portuguese (Brazil) (Free voice)"""
    DAICHI = "Daichi"
    """Male voice for Japanese (Japan) (Free voice)"""
    DALIA = "Dalia"
    """Female voice for Spanish (Mexico) (Free voice)"""
    DALIA_2 = "Dalia_2"
    """Female voice for Spanish (Mexico) (Free voice)"""
    DANIEL = "Daniel"
    """Male voice for German (Germany) (Free voice)"""
    DANIEL_2 = "Daniel_2"
    """Male voice for German (Germany) (Paid voice)"""
    DANIELLE = "Danielle"
    """Female voice for English (United States) (Free voice)"""
    DANIELLE_2 = "Danielle_2"
    """Female voice for English (United States) (Paid voice)"""
    DARIO = "Dario"
    """Male voice for Spanish (Spain) (Free voice)"""
    DARIYA = "Dariya"
    """Female voice for Russian (Russia) (Free voice)"""
    DARREN = "Darren"
    """Male voice for English (Australia) (Free voice)"""
    DAUDI = "Daudi"
    """Male voice for Swahili (Tanzania) (Free voice)"""
    DAULET = "Daulet"
    """Male voice for Kazakh (Kazakhstan) (Free voice)"""
    DAVIS = "Davis"
    """Male voice for English (United States) (Free voice)"""
    DAVIS_2 = "Davis_2"
    """Male voice for English (United States) (Free voice)"""
    DAVIS_3 = "Davis_3"
    """Male voice for English (United States) (Paid voice)"""
    DENA = "Dena"
    """Female voice for Dutch (Belgium) (Free voice)"""
    DENISE = "Denise"
    """Female voice for French (France) (Free voice)"""
    DEREK = "Derek"
    """Male voice for English (United States) (Free voice)"""
    DHWANI = "Dhwani"
    """Female voice for Gujarati (India) (Free voice)"""
    DIEGO = "Diego"
    """Male voice for Italian (Italy) (Free voice)"""
    DILARA = "Dilara"
    """Female voice for Persian (Iran) (Free voice)"""
    DIMAS = "Dimas"
    """Male voice for Javanese (Latin, Indonesia) (Free voice)"""
    DMITRY = "Dmitry"
    """Male voice for Russian (Russia) (Free voice)"""
    DONATO = "Donato"
    """Male voice for Portuguese (Brazil) (Free voice)"""
    DORA = "Dora"
    """Female voice for Icelandic (Iceland) (Free voice)"""
    DUARTE = "Duarte"
    """Male voice for Portuguese (Portugal) (Free voice)"""
    DUNCAN = "Duncan"
    """Male voice for English (Australia) (Free voice)"""
    DUSTIN = "Dustin"
    """Male voice for English (United States) (Free voice)"""
    ECHO = "Echo"
    """Male voice for English (United States) (Free voice)"""
    EKA = "Eka"
    """Female voice for Georgian (Georgia) (Free voice)"""
    ELENA = "Elena"
    """Female voice for Spanish (Argentina) (Free voice)"""
    ELIAS = "Elias"
    """Male voice for Spanish (Spain) (Free voice)"""
    ELIMU = "Elimu"
    """Male voice for English (Tanzania) (Free voice)"""
    ELIN = "Elin"
    """Female voice for Swedish (Sweden) (Free voice)"""
    ELIZABETH = "Elizabeth"
    """Female voice for English (United States) (Free voice)"""
    ELKE = "Elke"
    """Female voice for German (Germany) (Free voice)"""
    ELLIOT = "Elliot"
    """Male voice for English (United Kingdom) (Free voice)"""
    ELOISE = "Eloise"
    """Female voice for French (France) (Free voice)"""
    ELSA = "Elsa"
    """Female voice for Italian (Italy) (Free voice)"""
    ELSIE = "Elsie"
    """Female voice for English (Australia) (Free voice)"""
    ELVIRA = "Elvira"
    """Female voice for Spanish (Spain) (Free voice)"""
    ELZA = "Elza"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    EMEL = "Emel"
    """Female voice for Turkish (Türkiye) (Free voice)"""
    EMIL = "Emil"
    """Male voice for Romanian (Romania) (Free voice)"""
    EMILIO = "Emilio"
    """Male voice for Spanish (Dominican Republic) (Free voice)"""
    EMILY = "Emily"
    """Female voice for English (Ireland) (Free voice)"""
    EMMA = "Emma"
    """Female voice for English (United States) (Free voice)"""
    EMMA_2 = "Emma_2"
    """Female voice for English (United States) (Free voice)"""
    EMMA_3 = "Emma_3"
    """Female voice for English (United States) (Paid voice)"""
    EMMA_4 = "Emma_4"
    """Female voice for English (United States) (Paid voice)"""
    ENRIC = "Enric"
    """Male voice for Catalan (Free voice)"""
    ENRIQUE = "Enrique"
    """Male voice for Spanish (Castilian) (Free voice)"""
    ERIC = "Eric"
    """Male voice for English (United States) (Free voice)"""
    ESTRELLA = "Estrella"
    """Female voice for Spanish (Spain) (Free voice)"""
    ETHAN = "Ethan"
    """Male voice for English (United Kingdom) (Free voice)"""
    EVELYN = "Evelyn"
    """Female voice for English (United States) (Free voice)"""
    EVERITA = "Everita"
    """Female voice for Latvian (Latvia) (Free voice)"""
    EWA = "Ewa"
    """Female voice for Polish (Poland) (Free voice)"""
    EWA_2 = "Ewa_2"
    """Female voice for Polish (Poland) (Paid voice)"""
    EZINNE = "Ezinne"
    """Female voice for English (Nigeria) (Free voice)"""
    FABIO = "Fabio"
    """Male voice for Portuguese (Brazil) (Free voice)"""
    FABIOLA = "Fabiola"
    """Female voice for Italian (Italy) (Free voice)"""
    FABLE = "Fable"
    """Neutral voice for English (United States) (Free voice)"""
    FABRICE = "Fabrice"
    """Male voice for French (Switzerland) (Free voice)"""
    FAHED = "Fahed"
    """Male voice for Arabic (Kuwait) (Free voice)"""
    FARID = "Farid"
    """Male voice for Persian (Iran) (Free voice)"""
    FATIMA = "Fatima"
    """Female voice for Arabic (United Arab Emirates) (Free voice)"""
    FEDERICO = "Federico"
    """Male voice for Spanish (Nicaragua) (Free voice)"""
    FENNA = "Fenna"
    """Female voice for Dutch (Netherlands) (Free voice)"""
    FERNANDA = "Fernanda"
    """Female voice for Portuguese (Portugal) (Free voice)"""
    FIAMMA = "Fiamma"
    """Female voice for Italian (Italy) (Free voice)"""
    FILIZ = "Filiz"
    """Female voice for Turkish (Türkiye) (Free voice)"""
    FINN = "Finn"
    """Male voice for Norwegian (Norway) (Free voice)"""
    FLORIAN = "Florian"
    """Male voice for German (Germany) (Free voice)"""
    FLORIAN_2 = "Florian_2"
    """Male voice for German (Germany) (Paid voice)"""
    FLORIN = "Florin"
    """Male voice for French (France) (Paid voice)"""
    FRANCISCA = "Francisca"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    FREYA = "Freya"
    """Female voice for English (Australia) (Free voice)"""
    GABRIELLE = "Gabrielle"
    """Female voice for French (Canada) (Free voice)"""
    GABRIELLE_2 = "Gabrielle_2"
    """Female voice for French (Canada) (Paid voice)"""
    GABRIJELA = "Gabrijela"
    """Female voice for Croatian (Croatia) (Free voice)"""
    GADIS = "Gadis"
    """Female voice for Indonesian (Indonesia) (Free voice)"""
    GAGAN = "Gagan"
    """Male voice for Kannada (India) (Free voice)"""
    GEMMA = "Gemma"
    """Female voice for English (United Kingdom) (Free voice)"""
    GEMMA_2 = "Gemma_2"
    """Female voice for English (United Kingdom) (Free voice)"""
    GERAINT = "Geraint"
    """Male voice for Welsh (United Kingdom) (Free voice)"""
    GERARD = "Gerard"
    """Male voice for French (Belgium) (Free voice)"""
    GERARDO = "Gerardo"
    """Male voice for Spanish (Mexico) (Free voice)"""
    GIANNI = "Gianni"
    """Male voice for Italian (Italy) (Free voice)"""
    GIORGI = "Giorgi"
    """Male voice for Georgian (Georgia) (Free voice)"""
    GIORGIO = "Giorgio"
    """Male voice for Italian (Italy) (Free voice)"""
    GIOVANNA = "Giovanna"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    GISELA = "Gisela"
    """Female voice for German (Germany) (Free voice)"""
    GIUSEPPE = "Giuseppe"
    """Male voice for Italian (Italy) (Free voice)"""
    GIUSEPPE_2 = "Giuseppe_2"
    """Male voice for Italian (Italy) (Free voice)"""
    GONZALO = "Gonzalo"
    """Male voice for Spanish (Colombia) (Free voice)"""
    GOOKMIN = "GookMin"
    """Male voice for Korean (Korea) (Free voice)"""
    GORAN = "Goran"
    """Male voice for Bosnian (Bosnia and Herzegovina) (Free voice)"""
    GRACE = "Grace"
    """Female voice for Maltese (Malta) (Free voice)"""
    GREGORY = "Gregory"
    """Male voice for English (United States) (Free voice)"""
    GUDRUN = "Gudrun"
    """Female voice for Icelandic (Iceland) (Free voice)"""
    GUL = "Gul"
    """Female voice for Urdu (India) (Free voice)"""
    GULNAWAZ = "GulNawaz"
    """Male voice for Pashto (Afghanistan) (Free voice)"""
    GUNNAR = "Gunnar"
    """Male voice for Icelandic (Iceland) (Free voice)"""
    GUY = "Guy"
    """Male voice for English (United States) (Free voice)"""
    GWYNETH = "Gwyneth"
    """Female voice for Welsh (United Kingdom) (Free voice)"""
    HALA = "Hala"
    """Female voice for Arabic (Saudi Arabia) (Free voice)"""
    HAMDAN = "Hamdan"
    """Male voice for Arabic (United Arab Emirates) (Free voice)"""
    HAMED = "Hamed"
    """Male voice for Arabic (Saudi Arabia) (Free voice)"""
    HANNAH = "Hannah"
    """Female voice for German (Austria) (Free voice)"""
    HANNAH_2 = "Hannah_2"
    """Female voice for German (Austria) (Paid voice)"""
    HANS = "Hans"
    """Male voice for German (Germany) (Free voice)"""
    HARRI = "Harri"
    """Male voice for Finnish (Finland) (Free voice)"""
    HAYK = "Hayk"
    """Male voice for Armenian (Armenia) (Free voice)"""
    HEDI = "Hedi"
    """Male voice for Arabic (Tunisia) (Free voice)"""
    HEMKALA = "Hemkala"
    """Female voice for Nepali (Nepal) (Free voice)"""
    HENRI = "Henri"
    """Male voice for French (France) (Free voice)"""
    HILA = "Hila"
    """Female voice for Hebrew (Israel) (Free voice)"""
    HILLEVI = "Hillevi"
    """Female voice for Swedish (Sweden) (Free voice)"""
    HIUGAAI = "HiuGaai"
    """Female voice for Chinese (Cantonese, Traditional) (Free voice)"""
    HIUJIN = "Hiujin"
    """Female voice for Chinese (Cantonese) (Free voice)"""
    HIUMAAN = "HiuMaan"
    """Female voice for Chinese (Cantonese, Traditional) (Free voice)"""
    HOAIMY = "HoaiMy"
    """Female voice for Vietnamese (Vietnam) (Free voice)"""
    HOLLIE = "Hollie"
    """Female voice for English (United Kingdom) (Free voice)"""
    HSIAOCHEN = "HsiaoChen"
    """Female voice for Chinese (Taiwanese Mandarin, Traditional) (Free voice)"""
    HSIAOYU = "HsiaoYu"
    """Female voice for Chinese (Taiwanese Mandarin, Traditional) (Free voice)"""
    HUMBERTO = "Humberto"
    """Male voice for Portuguese (Brazil) (Free voice)"""
    HYUNSU = "Hyunsu"
    """Male voice for Korean (Korea) (Free voice)"""
    HYUNSU_2 = "Hyunsu_2"
    """Male voice for Korean (Korea) (Free voice)"""
    HYUNSU_3 = "Hyunsu_3"
    """Male voice for Korean (Korea) (Paid voice)"""
    IDA = "Ida"
    """Female voice for Norwegian (Norway) (Free voice)"""
    ILIR = "Ilir"
    """Male voice for Albanian (Albania) (Free voice)"""
    IMAN = "Iman"
    """Female voice for Arabic (Libya) (Free voice)"""
    IMANI = "Imani"
    """Female voice for English (Tanzania) (Free voice)"""
    IMELDA = "Imelda"
    """Female voice for Italian (Italy) (Free voice)"""
    INES = "Ines"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    INES_2 = "Ines_2"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    INGRID = "Ingrid"
    """Female voice for German (Austria) (Free voice)"""
    INJOON = "InJoon"
    """Male voice for Korean (Korea) (Free voice)"""
    IRENE = "Irene"
    """Female voice for Spanish (Spain) (Free voice)"""
    IRMA = "Irma"
    """Female voice for Italian (Italy) (Free voice)"""
    ISABELLA = "Isabella"
    """Female voice for Italian (Italy) (Free voice)"""
    ISABELLA_2 = "Isabella_2"
    """Female voice for Italian (Italy) (Free voice)"""
    ISABELLA_3 = "Isabella_3"
    """Female voice for Italian (Italy) (Paid voice)"""
    ISABELLE = "Isabelle"
    """Female voice for French (Belgium) (Free voice)"""
    ISABELLE_2 = "Isabelle_2"
    """Female voice for French (Belgium) (Paid voice)"""
    ISELIN = "Iselin"
    """Female voice for Norwegian (Norway) (Free voice)"""
    ISIDORA = "Isidora"
    """Female voice for Spanish (Spain) (Free voice)"""
    ISMAEL = "Ismael"
    """Male voice for Arabic (Algeria) (Free voice)"""
    IVY = "Ivy"
    """Female voice for English (United States) (Free voice)"""
    IVY_2 = "Ivy_2"
    """Female voice for English (United States) (Free voice)"""
    JACEK = "Jacek"
    """Male voice for Polish (Poland) (Free voice)"""
    JACOB = "Jacob"
    """Male voice for English (United States) (Free voice)"""
    JACQUELINE = "Jacqueline"
    """Female voice for French (France) (Free voice)"""
    JAJANG = "Jajang"
    """Male voice for Sundanese (Indonesia) (Free voice)"""
    JAMAL = "Jamal"
    """Male voice for Arabic (Morocco) (Free voice)"""
    JAMES = "James"
    """Male voice for English (Philippines) (Free voice)"""
    JAN = "Jan"
    """Male voice for German (Switzerland) (Free voice)"""
    JANE = "Jane"
    """Female voice for English (United States) (Free voice)"""
    JANE_2 = "Jane_2"
    """Female voice for English (United States) (Paid voice)"""
    JANN = "Jann"
    """Male voice for Polish (Poland) (Free voice)"""
    JASMINE = "Jasmine"
    """Female voice for English (Singapore) (Free voice)"""
    JASMINE_2 = "Jasmine_2"
    """Female voice for English (Singapore) (Paid voice)"""
    JASON = "Jason"
    """Male voice for English (United States) (Free voice)"""
    JAVIER = "Javier"
    """Male voice for Spanish (Equatorial Guinea) (Free voice)"""
    JEAN = "Jean"
    """Male voice for French (Canada) (Free voice)"""
    JENNY = "Jenny"
    """Female voice for English (United States) (Free voice)"""
    JENNY_2 = "Jenny_2"
    """Female voice for English (United States) (Free voice)"""
    JENNY_3 = "Jenny_3"
    """Female voice for English (United States) (Paid voice)"""
    JEPPE = "Jeppe"
    """Male voice for Danish (Denmark) (Free voice)"""
    JEROME = "Jerome"
    """Male voice for French (France) (Free voice)"""
    JIHYE = "Jihye"
    """Female voice for Korean (Korea) (Free voice)"""
    JIMIN = "JiMin"
    """Female voice for Korean (Korea) (Free voice)"""
    JIMMIE = "Jimmie"
    """Male voice for English (United States) (Free voice)"""
    JITKA = "Jitka"
    """Female voice for Czech (Czechia) (Free voice)"""
    JOANA = "Joana"
    """Female voice for Catalan (Free voice)"""
    JOANNA = "Joanna"
    """Female voice for English (United States) (Free voice)"""
    JOANNA_2 = "Joanna_2"
    """Female voice for English (United States) (Free voice)"""
    JOANNA_3 = "Joanna_3"
    """Female voice for English (United States) (Paid voice)"""
    JOANNE = "Joanne"
    """Female voice for English (Australia) (Free voice)"""
    JOEY = "Joey"
    """Male voice for English (United States) (Free voice)"""
    JOEY_2 = "Joey_2"
    """Male voice for English (United States) (Free voice)"""
    JONAS = "Jonas"
    """Male voice for German (Austria) (Free voice)"""
    JORGE = "Jorge"
    """Male voice for Spanish (Mexico) (Free voice)"""
    JORGE_2 = "Jorge_2"
    """Male voice for Spanish (Mexico) (Free voice)"""
    JOSEPH = "Joseph"
    """Male voice for Maltese (Malta) (Free voice)"""
    JOSEPHINE = "Josephine"
    """Female voice for French (France) (Free voice)"""
    JUAN = "Juan"
    """Male voice for Spanish (Costa Rica) (Free voice)"""
    JULIO = "Julio"
    """Male voice for Portuguese (Brazil) (Free voice)"""
    JUSTIN = "Justin"
    """Male voice for English (United States) (Free voice)"""
    JUSTIN_2 = "Justin_2"
    """Male voice for English (United States) (Free voice)"""
    KAI = "Kai"
    """Male voice for English (United States) (Free voice)"""
    KAJAL = "Kajal"
    """Female voice for English (India) (Free voice)"""
    KAJAL_2 = "Kajal_2"
    """Female voice for English (India) (Paid voice)"""
    KALINA = "Kalina"
    """Female voice for Bulgarian (Bulgaria) (Free voice)"""
    KANI = "Kani"
    """Female voice for Tamil (Malaysia) (Free voice)"""
    KARINA = "Karina"
    """Female voice for Spanish (Puerto Rico) (Free voice)"""
    KARL = "Karl"
    """Male voice for Icelandic (Iceland) (Free voice)"""
    KARLA = "Karla"
    """Female voice for Spanish (Honduras) (Free voice)"""
    KASPER = "Kasper"
    """Male voice for German (Germany) (Free voice)"""
    KATJA = "Katja"
    """Female voice for German (Germany) (Free voice)"""
    KAVYA = "Kavya"
    """Female voice for Hindi (India) (Free voice)"""
    KAVYA_2 = "Kavya_2"
    """Female voice for English (India) (Free voice)"""
    KAZUHA = "Kazuha"
    """Female voice for Japanese (Japan) (Free voice)"""
    KEITA = "Keita"
    """Male voice for Japanese (Japan) (Free voice)"""
    KEN = "Ken"
    """Male voice for English (Australia) (Free voice)"""
    KENDRA = "Kendra"
    """Female voice for English (United States) (Free voice)"""
    KENDRA_2 = "Kendra_2"
    """Female voice for English (United States) (Free voice)"""
    KEOMANY = "Keomany"
    """Female voice for Lao (Laos) (Free voice)"""
    KERT = "Kert"
    """Male voice for Estonian (Estonia) (Free voice)"""
    KEVIN = "Kevin"
    """Male voice for English (United States) (Free voice)"""
    KILLIAN = "Killian"
    """Male voice for German (Germany) (Free voice)"""
    KIM = "Kim"
    """Female voice for English (Australia) (Free voice)"""
    KIMBERLY = "Kimberly"
    """Female voice for English (United States) (Free voice)"""
    KIMBERLY_2 = "Kimberly_2"
    """Female voice for English (United States) (Free voice)"""
    KLARISSA = "Klarissa"
    """Female voice for German (Germany) (Free voice)"""
    KLAUS = "Klaus"
    """Male voice for German (Germany) (Free voice)"""
    KUMAR = "Kumar"
    """Male voice for Tamil (Sri Lanka) (Free voice)"""
    KUNAL = "Kunal"
    """Male voice for Hindi (India) (Free voice)"""
    KUNAL_2 = "Kunal_2"
    """Male voice for English (India) (Free voice)"""
    LAIA = "Laia"
    """Female voice for Spanish (Spain) (Free voice)"""
    LAILA = "Laila"
    """Female voice for Arabic (Bahrain) (Free voice)"""
    LAITH = "Laith"
    """Male voice for Arabic (Syria) (Free voice)"""
    LARISSA = "Larissa"
    """Female voice for Spanish (Mexico) (Free voice)"""
    LATIFA = "Latifa"
    """Female voice for Pashto (Afghanistan) (Free voice)"""
    LAURA = "Laura"
    """Female voice for Dutch (Netherlands) (Free voice)"""
    LAURA_2 = "Laura_2"
    """Female voice for Dutch (Netherlands) (Paid voice)"""
    LAYLA = "Layla"
    """Female voice for Arabic (Lebanon) (Free voice)"""
    LEA = "Lea"
    """Female voice for French (France) (Free voice)"""
    LEA_2 = "Lea_2"
    """Female voice for French (France) (Free voice)"""
    LEA_3 = "Lea_3"
    """Female voice for French (France) (Paid voice)"""
    LEAH = "Leah"
    """Female voice for English (South Africa) (Free voice)"""
    LEILA = "Leila"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    LENI = "Leni"
    """Female voice for German (Switzerland) (Free voice)"""
    LENNART = "Lennart"
    """Male voice for German (Germany) (Paid voice)"""
    LEONAS = "Leonas"
    """Male voice for Lithuanian (Lithuania) (Free voice)"""
    LETICIA = "Leticia"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    LEWIS = "Lewis"
    """Male voice for English (United States) (Free voice)"""
    LIA = "Lia"
    """Female voice for Spanish (Spain) (Free voice)"""
    LIAM = "Liam"
    """Male voice for English (Canada) (Free voice)"""
    LIAN = "Lian"
    """Male voice for French (Canada) (Free voice)"""
    LIAN_2 = "Lian_2"
    """Male voice for French (Canada) (Paid voice)"""
    LIBBY = "Libby"
    """Female voice for English (United Kingdom) (Free voice)"""
    LIBERTO = "Liberto"
    """Male voice for Spanish (Mexico) (Free voice)"""
    LISA = "Lisa"
    """Female voice for Dutch (Belgium) (Free voice)"""
    LISA_2 = "Lisa_2"
    """Female voice for Dutch (Belgium) (Paid voice)"""
    LISANDRO = "Lisandro"
    """Male voice for Italian (Italy) (Free voice)"""
    LIV = "Liv"
    """Female voice for Norwegian (Norway) (Free voice)"""
    LIVIA = "Livia"
    """Female voice for English (Australia) (Free voice)"""
    LIVIA_2 = "Livia_2"
    """Female voice for English (Australia) (Paid voice)"""
    LOLA = "Lola"
    """Female voice for English (United States) (Free voice)"""
    LORENA = "Lorena"
    """Female voice for Spanish (El Salvador) (Free voice)"""
    LORENZIO = "Lorenzio"
    """Male voice for Italian (Italy) (Paid voice)"""
    LORENZO = "Lorenzo"
    """Male voice for Spanish (Chile) (Free voice)"""
    LOTTE = "Lotte"
    """Female voice for Dutch (Netherlands) (Free voice)"""
    LOUISA = "Louisa"
    """Female voice for German (Germany) (Free voice)"""
    LUCIA = "Lucia"
    """Female voice for Spanish (Castilian) (Free voice)"""
    LUCIA_2 = "Lucia_2"
    """Female voice for Spanish (Castilian) (Free voice)"""
    LUCIA_3 = "Lucia_3"
    """Female voice for Spanish (Castilian) (Paid voice)"""
    LUCIANO = "Luciano"
    """Male voice for Spanish (Mexico) (Free voice)"""
    LUCIEN = "Lucien"
    """Male voice for French (France) (Free voice)"""
    LUIS = "Luis"
    """Male voice for Spanish (Ecuador) (Free voice)"""
    LUKAS = "Lukas"
    """Male voice for Slovak (Slovakia) (Free voice)"""
    LUKE = "Luke"
    """Male voice for English (South Africa) (Free voice)"""
    LUNA = "Luna"
    """Female voice for English (Singapore) (Free voice)"""
    LUNA_2 = "Luna_2"
    """Female voice for English (United States) (Free voice)"""
    LUPE = "Lupe"
    """Female voice for Spanish (United States) (Free voice)"""
    LUPE_2 = "Lupe_2"
    """Female voice for Spanish (United States) (Free voice)"""
    LUPE_3 = "Lupe_3"
    """Female voice for Spanish (United States) (Paid voice)"""
    MAARTEN = "Maarten"
    """Male voice for Dutch (Netherlands) (Free voice)"""
    MACERIO = "Macerio"
    """Male voice for Portuguese (Brazil) (Free voice)"""
    MACERIO_2 = "Macerio_2"
    """Male voice for Portuguese (Brazil) (Paid voice)"""
    MADHUR = "Madhur"
    """Male voice for Hindi (India) (Free voice)"""
    MADINA = "Madina"
    """Female voice for Uzbek (Latin, Uzbekistan) (Free voice)"""
    MADS = "Mads"
    """Male voice for Danish (Denmark) (Free voice)"""
    MAISIE = "Maisie"
    """Female voice for English (United Kingdom) (Free voice)"""
    MAJA = "Maja"
    """Female voice for German (Germany) (Free voice)"""
    MANOHAR = "Manohar"
    """Male voice for Marathi (India) (Free voice)"""
    MANUEL = "Manuel"
    """Male voice for Spanish (Cuba) (Free voice)"""
    MANUELA = "Manuela"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    MARCELLO = "Marcello"
    """Male voice for Italian (Italy) (Free voice)"""
    MARCELO = "Marcelo"
    """Male voice for Spanish (Bolivia) (Free voice)"""
    MAREK = "Marek"
    """Male voice for Polish (Poland) (Free voice)"""
    MARGARITA = "Margarita"
    """Female voice for Spanish (Panama) (Free voice)"""
    MARIA = "Maria"
    """Female voice for Spanish (Costa Rica) (Free voice)"""
    MARIJA = "Marija"
    """Female voice for Macedonian (North Macedonia) (Free voice)"""
    MARINA = "Marina"
    """Female voice for Spanish (Mexico) (Free voice)"""
    MARIO = "Mario"
    """Male voice for Spanish (Paraguay) (Free voice)"""
    MARLENE = "Marlene"
    """Female voice for German (Germany) (Free voice)"""
    MARTA = "Marta"
    """Female voice for Spanish (Guatemala) (Free voice)"""
    MARYAM = "Maryam"
    """Female voice for Arabic (Yemen) (Free voice)"""
    MASARU = "Masaru"
    """Male voice for Japanese (Japan) (Paid voice)"""
    MATEO = "Mateo"
    """Male voice for Spanish (Uruguay) (Free voice)"""
    MATHIEU = "Mathieu"
    """Male voice for French (France) (Free voice)"""
    MATTHEW = "Matthew"
    """Male voice for English (United States) (Free voice)"""
    MATTHEW_2 = "Matthew_2"
    """Male voice for English (United States) (Free voice)"""
    MATTHEW_3 = "Matthew_3"
    """Male voice for English (United States) (Paid voice)"""
    MATTIAS = "Mattias"
    """Male voice for Swedish (Sweden) (Free voice)"""
    MAURICE = "Maurice"
    """Male voice for French (France) (Free voice)"""
    MAXIM = "Maxim"
    """Male voice for Russian (Russia) (Free voice)"""
    MAYA = "Maya"
    """Female voice for Polish (Poland) (Free voice)"""
    MAYU = "Mayu"
    """Female voice for Japanese (Japan) (Free voice)"""
    MEKDES = "Mekdes"
    """Female voice for Amharic (Ethiopia) (Free voice)"""
    MIA = "Mia"
    """Female voice for Spanish (Mexico) (Free voice)"""
    MIA_2 = "Mia_2"
    """Female voice for Spanish (Mexico) (Free voice)"""
    MIA_3 = "Mia_3"
    """Female voice for Spanish (Mexico) (Paid voice)"""
    MICHELLE = "Michelle"
    """Female voice for English (United States) (Free voice)"""
    MIDHUN = "Midhun"
    """Male voice for Malayalam (India) (Free voice)"""
    MIGUEL = "Miguel"
    """Male voice for Spanish (United States) (Free voice)"""
    MITCHELL = "Mitchell"
    """Male voice for English (New Zealand) (Free voice)"""
    MIZUKI = "Mizuki"
    """Female voice for Japanese (Japan) (Free voice)"""
    MOAZ = "Moaz"
    """Male voice for Arabic (Qatar) (Free voice)"""
    MOHAN = "Mohan"
    """Male voice for Telugu (India) (Free voice)"""
    MOLLY = "Molly"
    """Female voice for English (New Zealand) (Free voice)"""
    MONICA = "Monica"
    """Female voice for English (United States) (Free voice)"""
    MOUNA = "Mouna"
    """Female voice for Arabic (Morocco) (Free voice)"""
    MUUSE = "Muuse"
    """Male voice for Somali (Somalia) (Free voice)"""
    NABANITA = "Nabanita"
    """Female voice for Bangla (Bangladesh) (Free voice)"""
    NAJA = "Naja"
    """Female voice for Danish (Denmark) (Free voice)"""
    NAMMINH = "NamMinh"
    """Male voice for Vietnamese (Vietnam) (Free voice)"""
    NANAMI = "Nanami"
    """Female voice for Japanese (Japan) (Free voice)"""
    NANAMI_2 = "Nanami_2"
    """Female voice for Japanese (Japan) (Paid voice)"""
    NANCY = "Nancy"
    """Female voice for English (United States) (Free voice)"""
    NANCY_2 = "Nancy_2"
    """Female voice for English (United States) (Free voice)"""
    NAOKI = "Naoki"
    """Male voice for Japanese (Japan) (Free voice)"""
    NATASHA = "Natasha"
    """Female voice for English (Australia) (Free voice)"""
    NEERJA = "Neerja"
    """Female voice for English (India) (Free voice)"""
    NEERJA_2 = "Neerja_2"
    """Female voice for English (India) (Free voice)"""
    NEIL = "Neil"
    """Male voice for English (Australia) (Free voice)"""
    NESTORAS = "Nestoras"
    """Male voice for Greek (Greece) (Free voice)"""
    NIA = "Nia"
    """Female voice for Welsh (United Kingdom) (Free voice)"""
    NIAMH = "Niamh"
    """Female voice for English (Ireland) (Free voice)"""
    NIAMH_2 = "Niamh_2"
    """Female voice for English (Ireland) (Paid voice)"""
    NICHOLAS = "Nicholas"
    """Male voice for Serbian (Cyrillic, Serbia) (Free voice)"""
    NICHOLAS_2 = "Nicholas_2"
    """Male voice for Serbian (Latin, Serbia) (Free voice)"""
    NICOLAU = "Nicolau"
    """Male voice for Portuguese (Brazil) (Free voice)"""
    NICOLE = "Nicole"
    """Female voice for English (Australia) (Free voice)"""
    NIL = "Nil"
    """Male voice for Spanish (Spain) (Free voice)"""
    NILAR = "Nilar"
    """Female voice for Burmese (Myanmar) (Free voice)"""
    NILS = "Nils"
    """Male voice for Latvian (Latvia) (Free voice)"""
    NIRANJAN = "Niranjan"
    """Male voice for Gujarati (India) (Free voice)"""
    NIWAT = "Niwat"
    """Male voice for Thai (Thailand) (Free voice)"""
    NOAH = "Noah"
    """Male voice for English (United Kingdom) (Free voice)"""
    NOEMI = "Noemi"
    """Female voice for Hungarian (Hungary) (Free voice)"""
    NOORA = "Noora"
    """Female voice for Finnish (Finland) (Free voice)"""
    NOURA = "Noura"
    """Female voice for Arabic (Kuwait) (Free voice)"""
    NOVA = "Nova"
    """Female voice for English (United States) (Free voice)"""
    NOVA_2 = "Nova_2"
    """Female voice for English (United States) (Paid voice)"""
    NURIA = "Nuria"
    """Female voice for Spanish (Mexico) (Free voice)"""
    OJAS = "Ojas"
    """Male voice for Punjabi (India) (Free voice)"""
    OLA = "Ola"
    """Female voice for Polish (Poland) (Free voice)"""
    OLA_2 = "Ola_2"
    """Female voice for Polish (Poland) (Paid voice)"""
    OLIVER = "Oliver"
    """Male voice for English (United Kingdom) (Free voice)"""
    OLIVIA = "Olivia"
    """Female voice for English (United Kingdom) (Free voice)"""
    OLLIE = "Ollie"
    """Male voice for English (United Kingdom) (Free voice)"""
    OLLIE_2 = "Ollie_2"
    """Male voice for English (United Kingdom) (Paid voice)"""
    OMAR = "Omar"
    """Male voice for Arabic (Libya) (Free voice)"""
    ONA = "Ona"
    """Female voice for Lithuanian (Lithuania) (Free voice)"""
    ONYX = "Onyx"
    """Male voice for English (United States) (Free voice)"""
    ORLA = "Orla"
    """Female voice for Irish (Ireland) (Free voice)"""
    OSMAN = "Osman"
    """Male voice for Malay (Malaysia) (Free voice)"""
    OSTAP = "Ostap"
    """Male voice for Ukrainian (Ukraine) (Free voice)"""
    PALLAVI = "Pallavi"
    """Female voice for Tamil (India) (Free voice)"""
    PALMIRA = "Palmira"
    """Female voice for Italian (Italy) (Free voice)"""
    PALOMA = "Paloma"
    """Female voice for Spanish (United States) (Free voice)"""
    PAOLA = "Paola"
    """Female voice for Spanish (Venezuela) (Free voice)"""
    PEDRO = "Pedro"
    """Male voice for Spanish (United States) (Free voice)"""
    PEDRO_2 = "Pedro_2"
    """Male voice for Spanish (United States) (Paid voice)"""
    PELAYO = "Pelayo"
    """Male voice for Spanish (Mexico) (Free voice)"""
    PENELOPE = "Penelope"
    """Female voice for Spanish (United States) (Free voice)"""
    PERNILLE = "Pernille"
    """Female voice for Norwegian (Norway) (Free voice)"""
    PETRA = "Petra"
    """Female voice for Slovenian (Slovenia) (Free voice)"""
    PHOEBE = "Phoebe"
    """Female voice for English (United States) (Free voice)"""
    PHOEBE_2 = "Phoebe_2"
    """Female voice for English (United States) (Paid voice)"""
    PIERINA = "Pierina"
    """Female voice for Italian (Italy) (Free voice)"""
    PISETH = "Piseth"
    """Male voice for Khmer (Cambodia) (Free voice)"""
    POLINA = "Polina"
    """Female voice for Ukrainian (Ukraine) (Free voice)"""
    PRABHAT = "Prabhat"
    """Male voice for English (India) (Free voice)"""
    PRABHAT_2 = "Prabhat_2"
    """Male voice for English (India) (Free voice)"""
    PRADEEP = "Pradeep"
    """Male voice for Bangla (Bangladesh) (Free voice)"""
    PREMWADEE = "Premwadee"
    """Female voice for Thai (Thailand) (Free voice)"""
    PRIYOM = "Priyom"
    """Male voice for Assamese (India) (Free voice)"""
    RAFIKI = "Rafiki"
    """Male voice for Swahili (Kenya) (Free voice)"""
    RALF = "Ralf"
    """Male voice for German (Germany) (Free voice)"""
    RAMI = "Rami"
    """Male voice for Arabic (Lebanon) (Free voice)"""
    RAMONA = "Ramona"
    """Female voice for Spanish (Dominican Republic) (Free voice)"""
    RANA = "Rana"
    """Female voice for Arabic (Iraq) (Free voice)"""
    RAQUEL = "Raquel"
    """Female voice for Portuguese (Portugal) (Free voice)"""
    RAVEENA = "Raveena"
    """Female voice for English (India) (Free voice)"""
    REEM = "Reem"
    """Female voice for Arabic (Tunisia) (Free voice)"""
    REHAAN = "Rehaan"
    """Male voice for Hindi (India) (Free voice)"""
    REHAAN_2 = "Rehaan_2"
    """Male voice for English (India) (Free voice)"""
    REHEMA = "Rehema"
    """Female voice for Swahili (Tanzania) (Free voice)"""
    REMI = "Remi"
    """Male voice for French (France) (Free voice)"""
    REMI_2 = "Remi_2"
    """Male voice for French (France) (Paid voice)"""
    REMY = "Remy"
    """Male voice for French (France) (Free voice)"""
    REMY_2 = "Remy_2"
    """Male voice for French (France) (Paid voice)"""
    RENATA = "Renata"
    """Female voice for Spanish (Mexico) (Free voice)"""
    RICARDO = "Ricardo"
    """Male voice for Portuguese (Brazil) (Free voice)"""
    RINALDO = "Rinaldo"
    """Male voice for Italian (Italy) (Free voice)"""
    ROBERTO = "Roberto"
    """Male voice for Spanish (Panama) (Free voice)"""
    RODRIGO = "Rodrigo"
    """Male voice for Spanish (El Salvador) (Free voice)"""
    ROGER = "Roger"
    """Male voice for English (United States) (Free voice)"""
    ROI = "Roi"
    """Male voice for Galician (Free voice)"""
    ROK = "Rok"
    """Male voice for Slovenian (Slovenia) (Free voice)"""
    ROSA = "Rosa"
    """Female voice for English (Philippines) (Free voice)"""
    RUBEN = "Ruben"
    """Male voice for Dutch (Netherlands) (Free voice)"""
    RUSSELL = "Russell"
    """Male voice for English (Australia) (Free voice)"""
    RUTH = "Ruth"
    """Female voice for English (United States) (Free voice)"""
    RUTH_2 = "Ruth_2"
    """Female voice for English (United States) (Paid voice)"""
    RYAN = "Ryan"
    """Male voice for English (United States) (Free voice)"""
    RYAN_2 = "Ryan_2"
    """Male voice for English (United Kingdom) (Free voice)"""
    SABELA = "Sabela"
    """Female voice for Galician (Free voice)"""
    SABRINA = "Sabrina"
    """Female voice for German (Switzerland) (Free voice)"""
    SABRINA_2 = "Sabrina_2"
    """Female voice for German (Switzerland) (Paid voice)"""
    SAGAR = "Sagar"
    """Male voice for Nepali (Nepal) (Free voice)"""
    SALEH = "Saleh"
    """Male voice for Arabic (Yemen) (Free voice)"""
    SALLI = "Salli"
    """Female voice for English (United States) (Free voice)"""
    SALLI_2 = "Salli_2"
    """Female voice for English (United States) (Free voice)"""
    SALLI_3 = "Salli_3"
    """Female voice for English (United States) (Paid voice)"""
    SALMA = "Salma"
    """Female voice for Arabic (Egypt) (Free voice)"""
    SALMAN = "Salman"
    """Male voice for Urdu (India) (Free voice)"""
    SALOME = "Salome"
    """Female voice for Spanish (Colombia) (Free voice)"""
    SAM = "Sam"
    """Male voice for English (Hong Kong SAR) (Free voice)"""
    SAMEERA = "Sameera"
    """Male voice for Sinhala (Sri Lanka) (Free voice)"""
    SAMUEL = "Samuel"
    """Male voice for English (United States) (Free voice)"""
    SANA = "Sana"
    """Female voice for Arabic (Jordan) (Free voice)"""
    SAPNA = "Sapna"
    """Female voice for Kannada (India) (Free voice)"""
    SARA = "Sara"
    """Female voice for English (United States) (Free voice)"""
    SARANYA = "Saranya"
    """Female voice for Tamil (Sri Lanka) (Free voice)"""
    SARDOR = "Sardor"
    """Male voice for Uzbek (Latin, Uzbekistan) (Free voice)"""
    SAUL = "Saul"
    """Male voice for Spanish (Spain) (Free voice)"""
    SEBASTIAN = "Sebastian"
    """Male voice for Spanish (Venezuela) (Free voice)"""
    SELMA = "Selma"
    """Female voice for Finnish (Finland) (Free voice)"""
    SEOHYEON = "SeoHyeon"
    """Female voice for Korean (Korea) (Free voice)"""
    SEOYEON = "Seoyeon"
    """Female voice for Korean (Korea) (Free voice)"""
    SEOYEON_2 = "Seoyeon_2"
    """Female voice for Korean (Korea) (Free voice)"""
    SEOYEON_3 = "Seoyeon_3"
    """Female voice for Korean (Korea) (Paid voice)"""
    SERAPHINA = "Seraphina"
    """Female voice for German (Germany) (Free voice)"""
    SERAPHINA_2 = "Seraphina_2"
    """Female voice for German (Germany) (Paid voice)"""
    SERENA = "Serena"
    """Female voice for English (United States) (Free voice)"""
    SERENA_2 = "Serena_2"
    """Female voice for English (United States) (Paid voice)"""
    SERGIO = "Sergio"
    """Male voice for Spanish (Castilian) (Free voice)"""
    SERGIO_2 = "Sergio_2"
    """Male voice for Spanish (Castilian) (Paid voice)"""
    SHAKIR = "Shakir"
    """Male voice for Arabic (Egypt) (Free voice)"""
    SHIMMER = "Shimmer"
    """Female voice for English (United States) (Free voice)"""
    SHIORI = "Shiori"
    """Female voice for Japanese (Japan) (Free voice)"""
    SHRUTI = "Shruti"
    """Female voice for Telugu (India) (Free voice)"""
    SIQINIQ = "Siqiniq"
    """Female voice for Inuktitut (Syllabics, Canada) (Free voice)"""
    SIQINIQ_2 = "Siqiniq_2"
    """Female voice for Inuktitut (Latin, Canada) (Free voice)"""
    SITI = "Siti"
    """Female voice for Javanese (Latin, Indonesia) (Free voice)"""
    SOBHANA = "Sobhana"
    """Female voice for Malayalam (India) (Free voice)"""
    SOFFIE = "Soffie"
    """Female voice for Danish (Denmark) (Free voice)"""
    SOFIA = "Sofia"
    """Female voice for Spanish (Bolivia) (Free voice)"""
    SOFIE = "Sofie"
    """Female voice for Swedish (Sweden) (Free voice)"""
    SONIA = "Sonia"
    """Female voice for English (United Kingdom) (Free voice)"""
    SOONBOK = "SoonBok"
    """Female voice for Korean (Korea) (Free voice)"""
    SOPHIE = "Sophie"
    """Female voice for Serbian (Cyrillic, Serbia) (Free voice)"""
    SOPHIE_2 = "Sophie_2"
    """Female voice for Serbian (Latin, Serbia) (Free voice)"""
    SRECKO = "Srecko"
    """Male voice for Croatian (Croatia) (Free voice)"""
    SREYMOM = "Sreymom"
    """Female voice for Khmer (Cambodia) (Free voice)"""
    STEFFAN = "Steffan"
    """Male voice for English (United States) (Free voice)"""
    STEFFAN_2 = "Steffan_2"
    """Male voice for English (United States) (Free voice)"""
    STEFFAN_3 = "Steffan_3"
    """Male voice for English (United States) (Paid voice)"""
    STEPHEN = "Stephen"
    """Male voice for English (United States) (Free voice)"""
    STEPHEN_2 = "Stephen_2"
    """Male voice for English (United States) (Paid voice)"""
    SUBHASINI = "Subhasini"
    """Female voice for Odia (India) (Free voice)"""
    SUKANT = "Sukant"
    """Male voice for Odia (India) (Free voice)"""
    SUNHI = "SunHi"
    """Female voice for Korean (Korea) (Free voice)"""
    SUNHI_2 = "SunHi_2"
    """Female voice for Korean (Korea) (Paid voice)"""
    SURYA = "Surya"
    """Male voice for Tamil (Malaysia) (Free voice)"""
    SUVI = "Suvi"
    """Female voice for Finnish (Finland) (Free voice)"""
    SVETLANA = "Svetlana"
    """Female voice for Russian (Russia) (Free voice)"""
    SWARA = "Swara"
    """Female voice for Hindi (India) (Free voice)"""
    SYLVIE = "Sylvie"
    """Female voice for French (Canada) (Free voice)"""
    SYLVIE_2 = "Sylvie_2"
    """Female voice for French (Canada) (Paid voice)"""
    TAIM = "Taim"
    """Male voice for Arabic (Jordan) (Free voice)"""
    TAKUMI = "Takumi"
    """Male voice for Japanese (Japan) (Free voice)"""
    TAKUMI_2 = "Takumi_2"
    """Male voice for Japanese (Japan) (Free voice)"""
    TAMAS = "Tamas"
    """Male voice for Hungarian (Hungary) (Free voice)"""
    TANIA = "Tania"
    """Female voice for Spanish (Paraguay) (Free voice)"""
    TANISHAA = "Tanishaa"
    """Female voice for Bengali (India) (Free voice)"""
    TANJA = "Tanja"
    """Female voice for German (Germany) (Free voice)"""
    TAQQIQ = "Taqqiq"
    """Male voice for Inuktitut (Syllabics, Canada) (Free voice)"""
    TAQQIQ_2 = "Taqqiq_2"
    """Male voice for Inuktitut (Latin, Canada) (Free voice)"""
    TATYANA = "Tatyana"
    """Female voice for Russian (Russia) (Free voice)"""
    TEO = "Teo"
    """Male voice for Spanish (Spain) (Free voice)"""
    TERESA = "Teresa"
    """Female voice for Spanish (Equatorial Guinea) (Free voice)"""
    THALITA = "Thalita"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    THALITA_2 = "Thalita_2"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    THALITA_3 = "Thalita_3"
    """Female voice for Portuguese (Brazil) (Paid voice)"""
    THANDO = "Thando"
    """Female voice for Zulu (South Africa) (Free voice)"""
    THEMBA = "Themba"
    """Male voice for Zulu (South Africa) (Free voice)"""
    THIAGO = "Thiago"
    """Male voice for Portuguese (Brazil) (Free voice)"""
    THIERRY = "Thierry"
    """Male voice for French (Canada) (Free voice)"""
    THIERRY_2 = "Thierry_2"
    """Male voice for French (Canada) (Paid voice)"""
    THIHA = "Thiha"
    """Male voice for Burmese (Myanmar) (Free voice)"""
    THILINI = "Thilini"
    """Female voice for Sinhala (Sri Lanka) (Free voice)"""
    THOMAS = "Thomas"
    """Male voice for English (United Kingdom) (Free voice)"""
    TIANA = "Tiana"
    """Female voice for English (United States) (Free voice)"""
    TIFFANY = "Tiffany"
    """Female voice for English (United States) (Paid voice)"""
    TIM = "Tim"
    """Male voice for English (Australia) (Free voice)"""
    TINA = "Tina"
    """Female voice for English (Australia) (Free voice)"""
    TOMAS = "Tomas"
    """Male voice for Spanish (Argentina) (Free voice)"""
    TOMOKO = "Tomoko"
    """Female voice for Japanese (Japan) (Free voice)"""
    TONY = "Tony"
    """Male voice for English (United States) (Free voice)"""
    TRIANA = "Triana"
    """Female voice for Spanish (Spain) (Free voice)"""
    TRISTAN = "Tristan"
    """Male voice for Spanish (Mexico) (Paid voice)"""
    TRISTAN_ES = "Tristan_ES"
    """Male voice for Spanish (Spain) (Free voice)"""
    TRISTAN_ES_2 = "Tristan_ES_2"
    """Male voice for Spanish (Spain) (Paid voice)"""
    TUTI = "Tuti"
    """Female voice for Sundanese (Indonesia) (Free voice)"""
    TYLER = "Tyler"
    """Male voice for English (United States) (Free voice)"""
    UBAX = "Ubax"
    """Female voice for Somali (Somalia) (Free voice)"""
    UZMA = "Uzma"
    """Female voice for Urdu (Pakistan) (Free voice)"""
    VAANI = "Vaani"
    """Female voice for Punjabi (India) (Free voice)"""
    VALENTINA = "Valentina"
    """Female voice for Spanish (Uruguay) (Free voice)"""
    VALERIO = "Valerio"
    """Male voice for Portuguese (Brazil) (Free voice)"""
    VALLUVAR = "Valluvar"
    """Male voice for Tamil (India) (Free voice)"""
    VENBA = "Venba"
    """Female voice for Tamil (Singapore) (Free voice)"""
    VERA = "Vera"
    """Female voice for Spanish (Spain) (Free voice)"""
    VESNA = "Vesna"
    """Female voice for Bosnian (Bosnia and Herzegovina) (Free voice)"""
    VICKI = "Vicki"
    """Female voice for German (Germany) (Free voice)"""
    VICKI_2 = "Vicki_2"
    """Female voice for German (Germany) (Free voice)"""
    VICKI_3 = "Vicki_3"
    """Female voice for German (Germany) (Paid voice)"""
    VICTOR = "Victor"
    """Male voice for Spanish (Puerto Rico) (Free voice)"""
    VIKTORIA = "Viktoria"
    """Female voice for Slovak (Slovakia) (Free voice)"""
    VITORIA = "Vitoria"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    VITORIA_2 = "Vitoria_2"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    VIVIENNE = "Vivienne"
    """Female voice for French (France) (Free voice)"""
    VIVIENNE_2 = "Vivienne_2"
    """Female voice for French (France) (Paid voice)"""
    VLASTA = "Vlasta"
    """Female voice for Czech (Czechia) (Free voice)"""
    WANLUNG = "WanLung"
    """Male voice for Chinese (Cantonese, Traditional) (Free voice)"""
    WAYNE = "Wayne"
    """Male voice for English (Singapore) (Free voice)"""
    WILLEM = "Willem"
    """Male voice for Afrikaans (South Africa) (Free voice)"""
    WILLIAM = "William"
    """Male voice for English (Australia) (Free voice)"""
    WILLIAM_2 = "William_2"
    """Male voice for English (Australia) (Free voice)"""
    XIAOCHEN = "Xiaochen"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOCHEN_2 = "Xiaochen_2"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOCHEN_3 = "Xiaochen_3"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOCHEN_4 = "Xiaochen_4"
    """Female voice for Chinese (Mandarin, Simplified) (Paid voice)"""
    XIAOHAN = "Xiaohan"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOHAN_2 = "Xiaohan_2"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOMENG = "Xiaomeng"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOMIN = "XiaoMin"
    """Female voice for Chinese (Cantonese, Simplified) (Free voice)"""
    XIAOMO = "Xiaomo"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOQIU = "Xiaoqiu"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOROU = "Xiaorou"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAORUI = "Xiaorui"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOSHUANG = "Xiaoshuang"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOSHUANG_2 = "Xiaoshuang_2"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOSHUANG_3 = "Xiaoshuang_3"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOTONG = "Xiaotong"
    """Female voice for Chinese (Wu, Simplified) (Free voice)"""
    XIAOXIAO = "Xiaoxiao"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOXIAO_2 = "Xiaoxiao_2"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOXIAO_3 = "Xiaoxiao_3"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOXIAO_4 = "Xiaoxiao_4"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOXIAO_5 = "Xiaoxiao_5"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOYAN = "Xiaoyan"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOYI = "Xiaoyi"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOYI_2 = "Xiaoyi_2"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOYOU = "Xiaoyou"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOYOU_2 = "Xiaoyou_2"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOYOU_3 = "Xiaoyou_3"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOYU = "Xiaoyu"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOYU_2 = "Xiaoyu_2"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIAOZHEN = "Xiaozhen"
    """Female voice for Chinese (Mandarin, Simplified) (Free voice)"""
    XIMENA = "Ximena"
    """Female voice for Spanish (Mexico) (Paid voice)"""
    XIMENA_ES = "Ximena_ES"
    """Female voice for Spanish (Spain) (Free voice)"""
    XIMENA_ES_2 = "Ximena_ES_2"
    """Female voice for Spanish (Spain) (Free voice)"""
    XIMENA_ES_3 = "Ximena_ES_3"
    """Female voice for Spanish (Spain) (Paid voice)"""
    YAGO = "Yago"
    """Male voice for Spanish (Mexico) (Free voice)"""
    YAN = "Yan"
    """Female voice for English (Hong Kong SAR) (Free voice)"""
    YARA = "Yara"
    """Female voice for Portuguese (Brazil) (Free voice)"""
    YASHICA = "Yashica"
    """Female voice for Assamese (India) (Free voice)"""
    YASMIN = "Yasmin"
    """Female voice for Malay (Malaysia) (Free voice)"""
    YESUI = "Yesui"
    """Female voice for Mongolian (Mongolia) (Free voice)"""
    YOLANDA = "Yolanda"
    """Female voice for Spanish (Nicaragua) (Free voice)"""
    YUJIN = "YuJin"
    """Female voice for Korean (Korea) (Free voice)"""
    YUNDENG = "Yundeng"
    """Male voice for Chinese (Zhongyuan Mandarin Henan, Simplified) (Free voice)"""
    YUNFAN = "Yunfan"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNFAN_2 = "Yunfan_2"
    """Male voice for Chinese (Mandarin, Simplified) (Paid voice)"""
    YUNFENG = "Yunfeng"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNHAN = "Yunhan"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNHAO = "Yunhao"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNJHE = "YunJhe"
    """Male voice for Chinese (Taiwanese Mandarin, Traditional) (Free voice)"""
    YUNJIAN = "Yunjian"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNJIE = "Yunjie"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNSONG = "YunSong"
    """Male voice for Chinese (Cantonese, Simplified) (Free voice)"""
    YUNXI = "Yunxi"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNXI_2 = "Yunxi_2"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNXIA = "Yunxia"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNXIA_2 = "Yunxia_2"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNXIANG = "Yunxiang"
    """Male voice for Chinese (Jilu Mandarin, Simplified) (Free voice)"""
    YUNXIAO = "Yunxiao"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNXIAO_2 = "Yunxiao_2"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNYANG = "Yunyang"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNYE = "Yunye"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNYE_2 = "Yunye_2"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNYI = "Yunyi"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNYI_2 = "Yunyi_2"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNZE = "Yunze"
    """Male voice for Chinese (Mandarin, Simplified) (Free voice)"""
    YUNZHE = "Yunzhe"
    """Male voice for Chinese (Wu, Simplified) (Free voice)"""
    YVES = "Yves"
    """Male voice for French (France) (Free voice)"""
    YVETTE = "Yvette"
    """Female voice for French (France) (Free voice)"""
    ZARIYAH = "Zariyah"
    """Female voice for Arabic (Saudi Arabia) (Free voice)"""
    ZAYD = "Zayd"
    """Male voice for Arabic (Saudi Arabia) (Free voice)"""
    ZEINA = "Zeina"
    """Female voice for Arabic (Saudi Arabia) (Free voice)"""
    ZHIYU = "Zhiyu"
    """Female voice for Chinese (Mandarin) (Free voice)"""
    ZHIYU_2 = "Zhiyu_2"
    """Female voice for Chinese (Mandarin) (Free voice)"""
    ZOFIA = "Zofia"
    """Female voice for Polish (Poland) (Free voice)"""
    ZURI = "Zuri"
    """Female voice for Swahili (Kenya) (Free voice)"""
