from typing import Literal, Union
from pydantic import StrictStr


SmsErrorCode = Union[Literal[
    "ERROR_CODE_UNSPECIFIED",
    "INTERNAL_ERROR",
    "SMS_PROVISIONING_FAILED",
    "CAMPAIGN_PROVISIONING_FAILED",
    "CAMPAIGN_NOT_AVAILABLE",
    "EXCEEDED_10DLC_LIMIT",
    "NUMBER_PROVISIONING_FAILED",
    "PARTNER_SERVICE_UNAVAILABLE",
    "CAMPAIGN_PENDING_ACCEPTANCE",
    "MNO_SHARING_ERROR",
    "CAMPAIGN_EXPIRED",
    "CAMPAIGN_MNO_REJECTED",
    "CAMPAIGN_MNO_SUSPENDED",
    "CAMPAIGN_MNO_REVIEW",
    "INSUFFICIENT_BALANCE",
    "MOCK_CAMPAIGN_NOT_ALLOWED",
    "TFN_NOT_ALLOWED",
    "INVALID_NNID"
], StrictStr]
