import os
import sys

# Allow autodoc to import the sinch package from the project root
sys.path.insert(0, os.path.abspath(".."))
from sinch import __version__

# -- Project information -------------------------------------------------------

project = "Sinch Python SDK"
copyright = "2024, Sinch Developer Experience Team"
author = "Sinch Developer Experience Team"
release = __version__

# -- General configuration -----------------------------------------------------

extensions = [
    # Pulls docstrings from Python source into the generated .rst files
    "sphinx.ext.autodoc",
    # Adds [source] links that open the highlighted source file
    "sphinx.ext.viewcode",
]

# The .rst files under api/ are generated by the `sphinx-apidoc` CLI invoked
# from the Makefile (`make docs`), using the custom templates in
# _templates/apidoc/ to strip the "package" suffix and the
# "Subpackages"/"Submodules"/"Module contents" headings. The
# sphinx.ext.apidoc extension is intentionally NOT used because it ignores
# the template directory.

# -- sphinx.ext.autodoc --------------------------------------------------------

autodoc_default_options = {
    # Document all public members (methods, attributes, nested classes)
    "members": True,
    'undoc-members': True,
    # Show the class inheritance chain
    "show-inheritance": True,
    # Preserve the order in which members appear in the source file
    "member-order": "bysource",
}

# Render type hints as part of the parameter/return descriptions, not the signature
autodoc_typehints = "both"
python_maximum_signature_line_length = 88

# -- HTML output ---------------------------------------------------------------

html_theme = "sphinx_rtd_theme"

html_theme_options = {
    # Maximum depth of the navigation sidebar (-1 = unlimited)
    "navigation_depth": -1,
    # Keep all navigation entries expanded by default
    "collapse_navigation": False,
}

# Directory with extra static files (custom CSS, etc.), relative to this conf.py
html_static_path = ["_static"]

# Extra stylesheets loaded after the theme's own CSS
html_css_files = ["custom.css"]